import { readFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// The backend's API surface, plus which of it the UI can actually reach.
//
// ── Source of truth ──────────────────────────────────────────────────────────
// `docs/api/api-surface.json`, generated by ApiSurfaceContractTest from springdoc's /v3/api-docs
// — Spring's own handler mappings, i.e. what the application dispatches. That test fails when the
// committed digest drifts from the running app, so nothing here is a stale transcription.
//
// This replaced two earlier approaches, both of which were mirrors:
//   • `API_ROUTES` (the frontend's route table) — a CONSUMER of the API. An endpoint no route
//     called was invisible: 49 missing, 24 under a wrong verb, ~22 deal actions collapsed into
//     one path matching no controller. See e2e-real/helpers/surface.js.
//   • a JS regex parse of `*Controller.java` — correct in practice, but a second implementation
//     of Spring's own mapping resolution, with nothing guarding it against the real dispatcher.
//
// Node-only (readFileSync): used by vitest and by the Playwright suite, never shipped to a browser.

/**
 * Resolve a path relative to THIS module, in both runtimes that load it.
 *
 * Playwright imports it as a real ESM module, where `import.meta.url` is a `file:` URL. Vitest
 * transforms it, and `import.meta.url` is then not a `file:` URL — `fileURLToPath` throws
 * "The URL must be of scheme file". The fallback anchors on vitest's root, which is `frontend/`.
 */
function fromModule(relative) {
  try {
    return fileURLToPath(new URL(relative, import.meta.url));
  } catch {
    return new URL(relative, `file://${process.cwd()}/src/api/`).pathname;
  }
}

const read = (relative) => readFileSync(fromModule(relative), 'utf8');

const digest = () => JSON.parse(read('../../../docs/api/api-surface.json'));

/** Path variables are positional; their NAMES differ between client and server by design. */
export const normalisePath = (path) => path.replace(/\{[^}]*\}/g, '{}');

/** Every operation the backend serves, as `{ verb, path, key, deprecated }`. */
export function backendOperations() {
  const parsed = digest();
  const deprecated = new Set(parsed.deprecated ?? []);
  return parsed.operations.map((entry) => {
    const [verb, path] = entry.split(' ');
    return {
      verb,
      path,
      raw: entry,
      key: `${verb} ${normalisePath(path)}`,
      deprecated: deprecated.has(entry),
    };
  });
}

// ── Which hrApi methods a screen can actually reach ──────────────────────────
//
// The blind spot both previous guards shared: they compared DECLARATIONS. Driving every method
// hrApi exports (or grepping hrApi for route references) counts a method no screen ever calls as
// "reached", so its endpoint looks live when no user can get to it. 39 of hrApi's 261 methods are
// in that state.
//
// A regex is sound *here* specifically, and it was checked before being relied on: across all of
// `src/` outside the api layer there is no destructuring of `api` (`const { leave } = api` → zero
// hits) and no aliased import outside `src/api` itself, so every call site is literally
// `api.<namespace>.<method>(`. If that ever stops being true, `componentCalledMethods` will
// under-report and the reachability assertion will fail loudly rather than silently pass.

const SRC_ROOT = () => fromModule('..').replace(/\/$/, '');

function sourceFiles(root, { includeTests = false } = {}) {
  const files = [];
  const visit = (directory) => {
    for (const entry of readdirSync(directory)) {
      const full = `${directory}/${entry}`;
      if (statSync(full).isDirectory()) {
        visit(full);
      } else if (/\.(js|jsx)$/.test(entry)) {
        if (!includeTests && /\.test\.(js|jsx)$/.test(entry)) continue;
        files.push(full);
      }
    }
  };
  visit(root);
  return files;
}

/** Strip comments so prose mentioning a path or a method name is not read as a call. */
export const stripComments = (code) =>
  code.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/[^\n]*/g, '$1');

/**
 * `namespace.method` for every `api.<namespace>.<method>(` a non-test module outside `src/api/`
 * calls — i.e. everything a user can actually reach through the UI.
 */
export function componentCalledMethods(root = SRC_ROOT()) {
  const called = new Set();
  for (const file of sourceFiles(root)) {
    if (file.startsWith(`${root}/api/`)) continue;
    const code = stripComments(readFileSync(file, 'utf8'));
    // `?.(` as well as `(`: PayrollPage guards two calls with an optional call
    // (`api.payroll.suggestedInputs?.({...})`) so an older mock lacking the method degrades
    // instead of throwing. Matching only `(` misses those and reports their endpoints as
    // UI-unreachable — `GET /api/payroll/suggested-inputs` was a false positive on the first run.
    for (const match of code.matchAll(/\bapi\.([A-Za-z_$][\w$]*)\.([A-Za-z_$][\w$]*)\s*\??\.?\s*\(/g)) {
      called.add(`${match[1]}.${match[2]}`);
    }
  }
  return called;
}

/** Modules outside `src/api/` that hand-build an `/api/` path, escaping every contract guard. */
export function apiPathBypasses(root = SRC_ROOT()) {
  const offenders = [];
  for (const file of sourceFiles(root)) {
    if (file.startsWith(`${root}/api/`)) continue;
    const code = stripComments(readFileSync(file, 'utf8'));
    for (const match of code.matchAll(/['"`](\/api\/[^'"`]*)/g)) {
      offenders.push(`${file.replace(root, 'src')}: ${match[1]}`);
    }
  }
  return offenders;
}
