import { readFileSync, readdirSync, statSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { backendOperations, frontendCallSites } from './apiSurface.js';

// Reconciles the frontend's API calls against the endpoints the BACKEND actually serves.
//
// This is a different axis from contract.test.js. That file guards mockApi against hrApi — two
// frontend modules mirroring each other. Nothing guarded either of them against the Java service,
// so the frontend could call a path no controller maps, or a controller could go unreachable, and
// every suite stayed green.
//
// The backend side is docs/api/api-surface.json, generated by ApiSurfaceContractTest from
// springdoc's /v3/api-docs — Spring's own handler mappings. That test fails if the digest drifts,
// so the file this reads is never a stale transcription. Neither side is a mirror of the other.
//
// Measured when this was written (2026-08-14): 276 backend operations, 263 hrApi call sites
// resolving to 255 distinct endpoints, 0 calls to an endpoint that does not exist, 21 endpoints
// the frontend never reaches.

/**
 * Backend endpoints no frontend code path reaches, each with the reason it is unreachable.
 *
 * This is an allowlist, not a scoreboard: an entry means "we looked, and here is why". A NEW
 * unreachable endpoint fails the suite rather than joining a silent pile — which is the whole
 * point, because an endpoint the frontend cannot reach is also the endpoint no UI test, no
 * journey spec and no manual QA pass will ever exercise.
 *
 * Removing a line is how you record that a surface got wired up. Adding one requires a reason a
 * reviewer can disagree with.
 */
const UNCALLED = {
  // ── Not browser-reachable by design ───────────────────────────────────────────────────────
  // Scanner devices authenticate with an X-GLR-Agent-Token header, not a session — which is
  // exactly why SecurityConfig allowlists this one path anonymously. No browser calls it.
  'POST /api/attendance/punch': 'device-only: scanner agents post punches with X-GLR-Agent-Token',
  'POST /api/attendance/devices/{deviceCode}/agent-token':
    'ops-only: rotates a scanner device token, run out-of-band rather than from the portal',

  // ── Procurement: backend shipped, no UI ───────────────────────────────────────────────────
  // ProcurementController is complete and reachable over HTTP, but routes.js declares no path to
  // any of it, so the factory purchase-order flow cannot be driven from the portal at all.
  'GET /api/factory-purchase-orders': 'procurement UI unshipped — no route in routes.js',
  'GET /api/factory-purchase-orders/{id}': 'procurement UI unshipped — no route in routes.js',
  'POST /api/factory-purchase-orders/{id}/cancel': 'procurement UI unshipped',
  'POST /api/factory-purchase-orders/{id}/goods-received': 'procurement UI unshipped',
  'POST /api/factory-purchase-orders/{id}/proforma': 'procurement UI unshipped',
  'POST /api/factory-purchase-orders/{id}/shipping': 'procurement UI unshipped',
  'GET /api/pricing-requests/{id}/factory-purchase-orders': 'procurement UI unshipped',
  'POST /api/pricing-requests/{id}/factory-purchase-orders': 'procurement UI unshipped',

  // ── CEO pricing controls with no UI ───────────────────────────────────────────────────────
  'POST /api/pricing-decisions/{decisionId}/recalculate-cost':
    'no UI: distinct from pricingRequests.recalculateCosting, which drives /pricing-costings/{id}/recalculate',
  'PUT /api/pricing-decisions/{decisionId}/items/{itemId}/cost-override':
    'no UI: per-item CEO cost override has no control on the pricing-decision screen',
  'GET /api/deal-estimate-markup': 'no UI: CEO settings never reads the markup endpoint',
  'PUT /api/deal-estimate-markup': 'no UI: CEO settings never writes the markup endpoint',

  // Freight rate ROWS can only be added/removed here; CeoSettingsPage edits existing amounts
  // through the bulk pricingFormulaConfig.update POST and reads config.freightRates from that
  // payload, so there is no add/remove control and routes.js declares no path.
  'POST /api/pricing-formula-config/freight-rates': 'no UI: freight rows cannot be added from CEO settings',
  'DELETE /api/pricing-formula-config/freight-rates/{freightRateId}':
    'no UI: freight rows cannot be removed from CEO settings',

  // ── Payroll deduction administration, no UI ───────────────────────────────────────────────
  'GET /api/payroll/deduction-consents': 'no UI: written-consent records are managed outside the portal',
  'PUT /api/payroll/deduction-consents': 'no UI: written-consent records are managed outside the portal',
  'GET /api/payroll/deduction-shortfalls': 'no UI: shortfall report has no screen',

  // ── HR admin actions with no control ──────────────────────────────────────────────────────
  'POST /api/employees/{id}/reset-password': 'no UI: password reset is not exposed on the employee screen',
  // The GET side IS used (leave.downloadPolicyDocument); only the upload has no control.
  'POST /api/leave/policy-document': 'no UI: the policy document can be read but not replaced from the portal',
};

const backend = backendOperations();
const calls = frontendCallSites();
const backendKeys = new Set(backend.map((operation) => operation.key));
const calledKeys = new Set(calls.map((call) => call.key));

/** `UNCALLED` is keyed by the raw digest form; compare on the same normalised key as everything else. */
const normaliseKey = (raw) => {
  const [verb, path] = raw.split(' ');
  return `${verb} ${path.replace(/\{[^}]*\}/g, '{}')}`;
};

describe('frontend ↔ backend API reconciliation', () => {
  it('the surfaces are non-trivial — a broken resolver must fail loudly, not sweep nothing', () => {
    // Both sides silently resolving to nothing would make every assertion below vacuous.
    expect(backend.length).toBeGreaterThan(150);
    expect(calls.length).toBeGreaterThan(150);
  });

  it('every endpoint hrApi.js calls is one the backend actually serves', () => {
    const orphans = calls
      .filter((call) => !backendKeys.has(call.key))
      .map((call) => `${call.key}  (API_ROUTES.${call.name}, via ${call.via})`);

    // A failure here means the frontend calls a path or verb no controller maps — a 404/405 in
    // production that no frontend test can see, because mockApi answers it happily.
    expect(orphans).toEqual([]);
  });

  it('every backend endpoint is reachable from the frontend, or listed in UNCALLED with a reason', () => {
    const allowlisted = new Set(Object.keys(UNCALLED).map(normaliseKey));
    const unreachable = backend
      .filter((operation) => !calledKeys.has(operation.key))
      .filter((operation) => !allowlisted.has(operation.key))
      .map((operation) => operation.raw);

    // A failure here means a new endpoint shipped that no UI can reach. Either wire it up, or add
    // it to UNCALLED with the reason — but do so deliberately.
    expect(unreachable).toEqual([]);
  });

  it('every UNCALLED entry is a real endpoint that is still unreachable, with a written reason', () => {
    const stale = [];
    for (const [raw, reason] of Object.entries(UNCALLED)) {
      const key = normaliseKey(raw);
      if (!backendKeys.has(key)) stale.push(`${raw} — no longer exists on the backend; drop this entry`);
      else if (calledKeys.has(key)) stale.push(`${raw} — the frontend now calls it; drop this entry`);
      else if (!reason || reason.trim().length < 15) stale.push(`${raw} — reason is missing or too terse`);
    }
    // Without this the allowlist rots into a list of endpoints that no longer exist, and quietly
    // starts excusing endpoints nobody ever re-examined.
    expect(stale).toEqual([]);
  });

  it('no module outside src/api builds an /api/ path itself', () => {
    // A component that hand-builds a URL escapes every contract guard in this file and in
    // contract.test.js — it is invisible to both. Comments are stripped first: UpcomingHolidays
    // documents `/api/holidays` in prose precisely to explain that it does NOT call it.
    // process.cwd(), not import.meta.url: vitest transforms test files, so import.meta.url is not
    // a file: URL here and fileURLToPath throws. Vitest runs with frontend/ as the root.
    const root = `${process.cwd()}/src`;
    const offenders = [];

    const visit = (directory) => {
      for (const entry of readdirSync(directory)) {
        const full = `${directory}/${entry}`;
        if (statSync(full).isDirectory()) {
          visit(full);
          continue;
        }
        if (!/\.(js|jsx)$/.test(entry) || /\.test\.(js|jsx)$/.test(entry)) continue;
        if (full.includes('/src/api/')) continue; // the API layer is where paths belong
        const code = readFileSync(full, 'utf8')
          .replace(/\/\*[\s\S]*?\*\//g, '')
          .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
        for (const match of code.matchAll(/['"`](\/api\/[^'"`]*)/g)) {
          offenders.push(`${full.replace(root, 'src')}: ${match[1]}`);
        }
      }
    };
    visit(root);

    expect(offenders).toEqual([]);
  });
});
