export const API_ROUTES = {
  auth: {
    login: '/api/auth/login',
    logout: '/api/auth/logout',
    me: '/api/auth/me',
  },
  employees: {
    list: '/api/employees',
    create: '/api/employees',
    detail: (id) => `/api/employees/${id}`,
  },
  profileRequests: {
    list: '/api/profile-requests',
    create: '/api/profile-requests',
    detail: (id) => `/api/profile-requests/${id}`,
  },
  attendance: {
    punches: '/api/attendance/punches',
    importDat: '/api/attendance/imports/dat',
  },
  overtime: {
    list: '/api/overtime',
    create: '/api/overtime',
    employees: '/api/overtime/employees',
    approve: (id) => `/api/overtime/${id}/approve`,
    reject: (id) => `/api/overtime/${id}/reject`,
    cancel: (id) => `/api/overtime/${id}/cancel`,
  },
  leave: {
    list: '/api/leave',
    create: '/api/leave',
    employees: '/api/leave/employees',
    types: '/api/leave/types',
    balances: '/api/leave/balances',
    approve: (id) => `/api/leave/${id}/approve`,
    reject: (id) => `/api/leave/${id}/reject`,
    cancel: (id) => `/api/leave/${id}/cancel`,
  },
  tickets: {
    list: '/api/tickets',
    create: '/api/tickets',
    detail: (id) => `/api/tickets/${id}`,
    action: (id, action) => `/api/tickets/${id}/${action}`,
    editItems: (id) => `/api/tickets/${id}/items`,
  },
  dashboard: {
    summary: '/api/dashboard/summary',
  },
  notifications: {
    list: '/api/notifications',
    markRead: (id) => `/api/notifications/${id}/read`,
  },
  commissions: {
    list: '/api/commissions',
    create: '/api/commissions',
    deductions: (id) => `/api/commissions/${id}/deductions`,
    approve: (id) => `/api/commissions/${id}/approve`,
    clawback: (id) => `/api/commissions/${id}/clawback`,
    simulator: '/api/commissions/simulator',
    payrollReady: '/api/commissions/payroll-ready',
  },
  payroll: {
    current: '/api/payroll',
    preview: '/api/payroll/preview',
    process: '/api/payroll/process',
    bankExport: (periodId) => `/api/payroll/${periodId}/bank-export`,
  },
};

export const ROLE_PERMISSIONS = {
  canUseEmployeeExperience: ['employee'],
  canSubmitProfileRequests: ['employee'],
  canViewEmployees: ['hr'],
  canManageEmployees: ['hr'],
  canReviewProfileRequests: ['hr'],
  canViewAllAttendance: ['hr'],
  canImportAttendance: ['hr'],
  canViewAllOvertime: ['hr', 'ceo', 'admin'],
  canViewAllLeave: ['hr', 'ceo', 'admin'],
  canReviewLeave: ['hr', 'admin'],
  // Sales module
  canViewTickets: ['sales', 'import', 'ceo', 'admin'],
  canCreateTickets: ['sales', 'admin'],
  canPickupTickets: ['import', 'admin'],
  canProposePrices: ['import', 'admin'],
  canApproveReject: ['ceo', 'admin'],
  canGenerateQuotation: ['sales', 'admin'],
  canViewCommissions: ['sales', 'sales_manager', 'ceo', 'hr', 'admin'],
  canSubmitCommissions: ['sales', 'sales_manager', 'ceo', 'admin'],
  canApproveCommissions: ['sales_manager', 'ceo', 'admin'],
  canViewPayrollCommissions: ['hr', 'admin'],
  canManagePayroll: ['hr', 'admin'],
};
