import { describe, expect, it, vi } from 'vitest';
import {
  apiPathBypasses,
  backendOperations,
  componentCalledMethods,
  normalisePath,
  readUiReachable,
  UI_REACHABLE_UPDATE,
  writeUiReachable,
} from './apiSurface.js';

/**
 * THE GUARD THIS FILE EXISTS TO ADD — hrApi.js against the SPRING CONTROLLERS.
 *
 * `contract.test.js` already pins mockApi.js against hrApi.js in both directions. Nothing pinned
 * hrApi.js against the thing that actually answers its requests. A server endpoint added, removed,
 * renamed, or re-verbed had no tripwire at all: the frontend kept calling the old path, every
 * mock-driven test stayed green (the mock answers whatever hrApi asks), and the only place the
 * disagreement showed up was a 404 in production. That is the same unguarded-mirror family this
 * repo has been closing all week — `WIN_PROBABILITY_DEFAULTS` vs `WinProbabilityDefaults.java`,
 * `stageMeta.js` vs `DealStage` — one layer up.
 *
 * THREE DIRECTIONS, DELIBERATELY ASYMMETRIC:
 *
 *   1. client → server  (`hrApi calls no endpoint that does not exist`)  — HARD FAIL, no allowlist.
 *      A call with no endpoint behind it is already broken. There is no legitimate reason to have
 *      one, so there is no way to excuse one.
 *
 *   2. server → client  (`every endpoint is called, or listed in SERVER_ONLY`) — allowlisted.
 *      An endpoint with no hrApi caller is NOT automatically dead. It may be reached by the Python
 *      scanner agents, a script, the e2e suite, or a documented curl operation; or it may be a
 *      capability built backend-first whose UI has not landed. Deleting one on the strength of "no
 *      hrApi caller" would be a production break. So this direction reports and requires a written
 *      reason rather than assuming litter.
 *
 *   3. hrApi → the UI  (`every endpoint is reachable from a screen`) — allowlisted, and NEW.
 *      Directions 1 and 2 both compare DECLARATIONS. An hrApi method no component ever calls still
 *      counted as "reached", so its endpoint looked live when no user could get to it. 39 of
 *      hrApi's 261 methods are in that state. This direction is what makes "reachable" mean
 *      reachable; see UNREACHABLE_FROM_UI, and note that its entries are explicitly NOT verified.
 *
 * WHY THE CLIENT SIDE IS INSTRUMENTED RATHER THAN PARSED. hrApi.js does not hold paths; it composes
 * them — `withQuery(...)`, `API_ROUTES.tickets.action(id, 'close/confirm')`, template literals with
 * an appended `?reason=`, and a dozen bare `fetch()` calls for blob downloads and multipart uploads.
 * A regex over the source would have to re-implement all of that and would silently under-report the
 * moment someone composed a path a new way — failing GREEN, which is the failure mode this file is
 * here to prevent. Mocking `./client.js` and `globalThis.fetch` and then CALLING every method means
 * the captured set is what the code actually issues. `assertEveryMethodProbed` below then fails if
 * any method produced no observable request at all, so a method this harness cannot drive is a loud
 * error rather than a quiet omission from the comparison.
 *
 * WHY THE SERVER SIDE IS NO LONGER PARSED HERE. This file used to parse `*Controller.java` with a
 * JS regex, on the reasoning that Spring's own `RequestMappingHandlerMapping` lives in the JVM and
 * the comparison has to happen somewhere. That reasoning was sound and the parse was correct — it
 * agreed exactly with springdoc on all 276 operations. But it was a second implementation of
 * Spring's mapping resolution with nothing checking it against the real dispatcher, which is the
 * same unguarded-mirror shape one level down.
 *
 * The surface now comes from `docs/api/api-surface.json`, generated by the backend's
 * `ApiSurfaceContractTest` from springdoc's `/v3/api-docs` — the JVM introspecting itself — and
 * that test FAILS when the committed digest drifts from the running application. So the JSON read
 * here is not a transcription anyone maintains; it is the dispatcher's own answer, with a tripwire.
 * It also carries the `@Deprecated` subset, which the regex could see but which no longer needs a
 * second parser to stay in step.
 *
 * This consolidates two guards that briefly existed side by side — this file (PR #722, parsing
 * Java) and `reconcile.test.js` (PR #726, reading the digest) — which asserted overlapping
 * properties from different sources behind two separate allowlists. One endpoint, one allowlist,
 * one source of truth.
 */

// ─────────────────────────────────────────────────────────────────────────────
// The server surface
// ─────────────────────────────────────────────────────────────────────────────

const SERVER_ENDPOINTS = backendOperations();
const normaliseServerPath = normalisePath;

const endpointKey = (e) => `${e.verb} ${normaliseServerPath(e.path)}`;
const SERVER_KEYS = new Set(SERVER_ENDPOINTS.map(endpointKey));
const DEPRECATED_KEYS = new Set(SERVER_ENDPOINTS.filter((e) => e.deprecated).map(endpointKey));

// ─────────────────────────────────────────────────────────────────────────────
// Capturing what hrApi.js actually issues
// ─────────────────────────────────────────────────────────────────────────────

const CAPTURED = [];

vi.mock('./client.js', async () => {
  const actual = await vi.importActual('./client.js');
  return {
    ...actual,
    apiRequest: (path, options = {}) => {
      CAPTURED.push({ verb: (options.method ?? 'GET').toUpperCase(), rawPath: String(path) });
      return Promise.resolve({});
    },
    csrfHeaders: () => ({}),
  };
});

const { api } = await import('./hrApi.js');

/**
 * The sentinel every placeholder argument carries. Any path segment containing it is a path
 * VARIABLE — that is how a composed client path is matched against a server `{id}`.
 */
const SENTINEL = '__P__';

/**
 * Argument profiles, tried in order until one runs without throwing. Different methods want
 * different shapes: an id (string), a payload (object), and `priceImport.updateProfile` which
 * runs `JSON.parse(json)` on its argument and needs valid JSON text.
 */
const ARGUMENT_PROFILES = [() => SENTINEL, () => ({}), () => '{}', () => 1];

function normaliseClientPath(path) {
  return path
    .split('?')[0]
    .split('/')
    .map((segment) => (segment.includes(SENTINEL) || /^\d+$/.test(segment) ? '{}' : segment))
    .join('/');
}

/** Drive every hrApi method and return `{ calls, unprobed }`. */
function probeClient() {
  const previousFetch = globalThis.fetch;
  const previousFormData = globalThis.FormData;
  globalThis.fetch = (url, options = {}) => {
    CAPTURED.push({ verb: (options.method ?? 'GET').toUpperCase(), rawPath: String(url) });
    return Promise.resolve({
      ok: true,
      status: 200,
      json: async () => ({}),
      blob: async () => ({}),
      text: async () => '',
      headers: { get: () => 'application/json' },
    });
  };
  // jsdom's FormData rejects a plain object for `append`; hrApi passes File-shaped values.
  globalThis.FormData = class { append() {} };

  const calls = [];
  const unprobed = [];
  try {
    for (const [namespace, methods] of Object.entries(api)) {
      for (const [name, fn] of Object.entries(methods)) {
        if (typeof fn !== 'function') continue;
        const before = CAPTURED.length;
        let returnedPath = null;
        for (const profile of ARGUMENT_PROFILES) {
          try {
            // Arity is a lower bound: several methods declare fewer parameters than they use
            // via defaults, so pass a few extra — surplus arguments are ignored.
            const result = fn(...Array.from({ length: Math.max(fn.length, 4) }, profile));
            // `*Url` helpers return a path for a link or image attribute instead of fetching it.
            if (typeof result === 'string' && result.startsWith('/api')) returnedPath = result;
            break;
          } catch {
            // try the next profile
          }
        }
        const issued = CAPTURED.slice(before);
        for (const call of issued) {
          calls.push({ namespace, name, verb: call.verb, path: normaliseClientPath(call.rawPath) });
        }
        if (returnedPath) {
          calls.push({ namespace, name, verb: 'GET', path: normaliseClientPath(returnedPath) });
        }
        if (!issued.length && !returnedPath) unprobed.push(`${namespace}.${name}`);
      }
    }
  } finally {
    globalThis.fetch = previousFetch;
    globalThis.FormData = previousFormData;
  }
  return { calls, unprobed };
}

const { calls: CLIENT_CALLS, unprobed: UNPROBED_METHODS } = probeClient();

/** A HEAD probe (leave.policyDocumentAvailable) is answered by the GET mapping. */
const clientKey = ({ verb, path }) => `${verb === 'HEAD' ? 'GET' : verb} ${path}`;
const CLIENT_KEYS = new Set(CLIENT_CALLS.map(clientKey));

// Which of those calls a SCREEN can actually reach — see the Direction 3 block below. Defined
// here, next to CLIENT_KEYS, because the API_SURFACE_REPORT block further down reads it and
// module-level code runs top to bottom: declaring it beside its own describe() put it in the
// temporal dead zone and the report crashed with "Cannot access before initialization". That is
// env-gated code, so neither lint nor the suite would have caught it.
const UI_CALLED_METHODS = componentCalledMethods();
const UI_REACHABLE_KEYS = new Set(
  CLIENT_CALLS
    .filter((call) => UI_CALLED_METHODS.has(`${call.namespace}.${call.name}`))
    .map(clientKey),
);

// ─────────────────────────────────────────────────────────────────────────────
// Endpoints with no hrApi caller
// ─────────────────────────────────────────────────────────────────────────────
//
// Same spirit — and the same two-way enforcement — as contract.test.js's KNOWN_GAPS and
// ARITY_EXEMPTIONS: every entry must name a real, still-uncalled endpoint and carry a written
// reason. A stale entry is deleted by its own test below, so an endpoint that later gains a caller
// cannot leave a pre-approved hole behind it.
//
// AN ENTRY HERE IS NOT A CLAIM THAT THE ENDPOINT IS DEAD. Read each reason: some are reached by
// clients this harness cannot see (the Python scanner agents), and some are capabilities built
// backend-first whose UI has not landed. Whether to surface or retire any of them is a product
// decision, recorded in the PR that added this file — not something a test should decide.
const SERVER_ONLY = {
  // ── Live, via a client this harness cannot see ────────────────────────────
  'GET /api/public/brand/logo.png':
    'Fetched by the MAIL CLIENT, not by this app — it is the <img> src in the notification email '
    + 'templates, so the requester is Gmail/Outlook rendering a message, with no session and no hrApi '
    + 'call. Anonymous by necessity rather than oversight: an email client cannot authenticate, and '
    + "Gmail's image proxy fetches with no credentials at all. Serves one static asset and reads "
    + 'nothing. SecurityConfig scopes the exception to /api/public/brand/** specifically, NOT '
    + '/api/public/**, so admitting this endpoint did not open a namespace.',
  'POST /api/attendance/punch':
    'The physical scanners post here with an X-GLR-Agent-Token instead of a session — see '
    + 'agents/attendance/showroom_agent.py. One of SecurityConfig\'s anonymous exceptions, and pinned by '
    + 'e2e-real/api-surface.spec.js ANONYMOUS_ALLOWLIST. Live; deliberately not reachable from hrApi.js.',
  'POST /api/attendance/devices/{}/agent-token':
    'Mints/rotates the device token the punch endpoint above authenticates with. Run by hand from an HR session '
    + '(curl/Postman) — the runbook is agents/attendance/WAREHOUSE_SCANNER_SETUP.md, and three more files under '
    + '"ERP Documentation/" document the same call. The plaintext is shown exactly once, which is why there is no '
    + 'UI. Covered by AttendanceControllerTest. LIVE, not dead.',

  // ── Deliberately dormant: the UI was built, shipped, then removed ─────────
  // All eight ProcurementController mappings. PR #683 (ebaf6888, 2026-08-11) deleted the จัดซื้อ & นำเข้า
  // page and every client layer together, and its commit body states the backend was kept on purpose:
  // "left in place, dormant and with no frontend caller. Nothing is dropped". It even predicts this
  // guard under Known risks: "a future contract-style sweep will flag them as unreachable. That is
  // intended." 0 factory POs have ever existed in production. ProcurementService remains well covered
  // by ProcurementServiceIntegrationTest; only the HTTP door has nobody behind it.
  'GET /api/factory-purchase-orders': 'ProcurementController — dormant by owner ruling, PR #683. See the block comment above.',
  'GET /api/factory-purchase-orders/{}': 'ProcurementController — dormant by owner ruling, PR #683. See the block comment above.',
  'POST /api/factory-purchase-orders/{}/cancel': 'ProcurementController — dormant by owner ruling, PR #683. See the block comment above.',
  'POST /api/factory-purchase-orders/{}/goods-received': 'ProcurementController — dormant by owner ruling, PR #683. See the block comment above.',
  'POST /api/factory-purchase-orders/{}/proforma': 'ProcurementController — dormant by owner ruling, PR #683. See the block comment above.',
  'POST /api/factory-purchase-orders/{}/shipping': 'ProcurementController — dormant by owner ruling, PR #683. See the block comment above.',
  'GET /api/pricing-requests/{}/factory-purchase-orders': 'ProcurementController — dormant by owner ruling, PR #683. See the block comment above.',
  'POST /api/pricing-requests/{}/factory-purchase-orders': 'ProcurementController — dormant by owner ruling, PR #683. See the block comment above.',

  // ── Built backend-first; the UI pass has not landed ───────────────────────
  // The four pricing entries that stood here (recalculate-cost, cost-override, and the two
  // freight-rate rows) went with PR #769, which shipped their CEO costing UI. GET and PUT
  // /api/payroll/deduction-consents went in the same week — DeductionConsentsPage.jsx now reaches
  // the read half and DeductionConsentFormModal.jsx the write half (issue #744). The stale-entry
  // test below is what deletes an entry once its endpoint gains a caller.
  // POST /api/leave/policy-document was the last entry in this block until 2026-08-14 —
  // LeavePolicyDocumentPage.jsx now reaches it (issue #744), which also re-wires the GET half's
  // policyDocumentAvailable/downloadPolicyDocument to a screen for the first time since the PDF was
  // bundled at frontend/public/policy/ (2026-08-11 owner ruling). That bundled copy is still what
  // the leave page links; this endpoint is the server-side archive of record, not that reader.

  // ── The STORED ใบขอซื้อ aggregate — capability built backend-first, UI not landed ──────────
  // Nine routes for one document lifecycle: draft per brand, edit, issue (minting IR<yy><nnn> or
  // accepting an override), revise, delete, read, and print from the stored snapshot. All gated
  // {import, ceo} in ImportRequestService except required-by-note, which is SALES's field and carries
  // its own gate; all proven wrong-way-round against real Postgres by
  // StoredImportRequestIntegrationTest.
  //
  // Deliberately NOT wired into hrApi.js in the same change. This PR is a migration plus nine
  // endpoints plus fourteen integration tests; bundling the UI would make it unreviewable, and the
  // preview half of this feature shipped exactly this way (#812 backend, #816 UI) without trouble.
  // The PREVIEW routes remain live and reachable, so the form is still obtainable meanwhile — what is
  // missing is only the recorded, numbered version.
  'POST /api/tickets/{}/import-requests':
    'Raises one DRAFT per brand on the deal, skipping brands that already have a live form. The '
    + 'entry point for the stored lifecycle.',
  'GET /api/tickets/{}/import-requests':
    'The deal\'s stored forms, all versions, with each one\'s printed sheet count.',
  'GET /api/import-requests/{}':
    'One stored form by its own id, with its items and printed sheet count — the read the edit and '
    + 'issue screens will load before acting on a specific version.',
  'PATCH /api/import-requests/{}':
    'Edits a draft\'s body, or the import-owned footer of an issued form (those blocks are filled in '
    + 'by hand AFTER issue). PATCH semantics — an absent field is left alone, never blanked.',
  'POST /api/import-requests/{}/issue':
    'DRAFT -> ISSUED: mints IR<yy><nnn> from sales.document_sequence, or accepts a caller override '
    + 'without advancing the sequence, and supersedes the version it replaces.',
  'POST /api/import-requests/{}/revise':
    'Prepares a correction as a new DRAFT at the next version, copying the issued body. The previous '
    + 'version stays ISSUED until the replacement issues.',
  'DELETE /api/import-requests/{}':
    'Deletes a DRAFT. An issued form is never deleted — it is superseded.',
  'GET /api/import-requests/{}/file':
    'Prints a stored form from ITS OWN snapshot, so an issued document keeps saying what it said '
    + 'when it was signed even if the deal is later edited.',
  'PUT /api/tickets/{}/required-by-note':
    'Sets the deal-level "กำหนดวันที่ต้องการของ". The one route in this family that belongs to SALES '
    + '(deal owner or CEO) rather than import, gated from DealStage.ORDER_RECEIVED onward.',

  // The three ใบขอซื้อ (F-SM-001) GETs were listed here between #812 and this change, as a
  // capability built backend-first whose UI had not landed. They are gone rather than re-worded:
  // DealFulfilmentPanel's IR block now calls all three through api.importRequests, so they are
  // ordinary called endpoints and this test refuses to keep an exemption for them.

  // Both are {ceo}-only, proven wrong-way-round against real Postgres by
  // ThicknessDefaultIntegrationTest (every denied role rejected AND nothing written), and
  // mutation-checked by removing requireCeoRole from the PUT. Deliberately not wired into
  // hrApi.js yet: the CEO settings screen that will call them is a separate change.
  'GET /api/catalog/thickness-defaults':
    'Lists the (factory, collection) pairs whose catalogue rows carry no thickness, ordered by how '
    + 'many rows each would unblock. Four of the nine factory workbooks have no thickness column at '
    + 'all, so 9,411 rows cannot resolve a freight band and are unpriceable until a human supplies '
    + 'the number — V153 added the table, this reads the gap list.',
  'PUT /api/catalog/thickness-defaults':
    'Bulk-saves those defaults. Bulk rather than row-at-a-time because 244 pairs cover every gap and '
    + 'one sitting would otherwise be 244 round trips. A null thickness CLEARS an entry rather than '
    + 'storing zero, which would silently select the lowest freight band instead of refusing to price.',

  // GET/PUT /api/deal-estimate-markup were the two entries here until 2026-08-14. They are gone
  // rather than re-worded: issue #748's owner ruling deleted the controller, repository, DTOs, both
  // backend test classes and — by V145 — the V112 table itself, so there is no longer an endpoint
  // to exempt. The two frontend tests asserting the multiplier must NOT come back stay where they
  // are (TicketCreateModal.test.jsx, CeoSettingsPage.test.jsx); they guard the frontend, which is
  // where the misreading happened.
};

// ─────────────────────────────────────────────────────────────────────────────
// hrApi calls that reach a @Deprecated endpoint
// ─────────────────────────────────────────────────────────────────────────────
//
// The path-and-verb comparison above cannot see this class of divergence, and it is the one this
// audit actually found in the wild. V141 (PR #702) moved landed costing from Import to the CEO and
// SEVERED three write routes rather than deleting them: they are still routed, still match on path
// and verb, and throw 409 unconditionally. `PricingCostingController`'s own Javadoc says keeping the
// route shape is deliberate so "the client contract stays stable" while the backend is cleaned
// first.
//
// NO SCREEN REACHES THEM ANY MORE (2026-08-14). PR #760 took them out of Import's ส่งให้ CEO
// อนุมัติราคา chain, and #747 deleted the last four controls that drove them — which were
// unreachable for their whole existence anyway. What still calls them is hrApi.js, and through it
// mockApi.js: `mockApi.depositNotices.test.js` drives createCosting -> recalculate -> submit to get
// a request to READY_FOR_CEO_REVIEW, because mockApi's markFactoryQuoteReady does NOT auto-advance
// the way FactoryQuoteService.markReadyForCosting does. So finishing this migration means teaching
// the mock the backend's current behaviour first — a change to the default verification surface,
// not a deletion — and until then these three stay listed here rather than in SERVER_ONLY. The
// three matching UNREACHABLE_FROM_UI entries record the screen half of the same state.
//
// Listing them as an EXACT expectation, the same shape as api-surface.spec.js's KNOWN_SERVER_ERRORS:
// a NEW deprecated call site fails this test, and so does finishing the migration without removing
// the entry. Either direction should require a decision rather than passing quietly.
const CALLS_DEPRECATED = {
  'POST /api/pricing-requests/{}/costings':
    'pricingRequests.createCosting → severed by V141; the CEO equivalent is startPricingDecision. Always 409s.',
  'POST /api/pricing-costings/{}/recalculate':
    'pricingRequests.recalculateCosting → severed by V141; replaced by POST /api/pricing-decisions/{}/recalculate-cost, '
    + 'which is in SERVER_ONLY above because no client calls it yet. Always 409s.',
  'POST /api/pricing-costings/{}/submit':
    'pricingRequests.submitCosting → severed by V141; there is no Import-submitted costing to hand over any more. '
    + 'Always 409s.',
};

// ─────────────────────────────────────────────────────────────────────────────
// The assertions
// ─────────────────────────────────────────────────────────────────────────────

// The whole reconciliation, on demand:
//   cd frontend && API_SURFACE_REPORT=1 npx vitest run src/api/serverContract.test.js
// Printed rather than committed as a checked-in table, deliberately: a static 278-row list is a
// hand-maintained mirror of exactly the kind this file exists to guard against, and it would be
// stale the first time someone added an endpoint. See docs/api-surface-reconciliation.md.
if (process.env.API_SURFACE_REPORT) {
  const callersFor = (key) => CLIENT_CALLS
    .filter((c) => clientKey(c) === key)
    .map((c) => `${c.namespace}.${c.name}`);
  const lines = [
    `server mappings: ${SERVER_ENDPOINTS.length} (unique verb+path: ${SERVER_KEYS.size})`,
    `hrApi call sites: ${CLIENT_CALLS.length} (unique verb+path: ${CLIENT_KEYS.size})`,
    `reachable from a screen: ${UI_REACHABLE_KEYS.size}`,
    '',
    // The owning controller is no longer shown: the digest is verb+path only, deliberately, so
    // that its diff stays a readable record of contract changes. springdoc's `tags` carry the
    // controller if a triage ever needs it.
    '| Verb | Path | hrApi caller | reachable from a screen |',
    '|---|---|---|---|',
  ];
  for (const e of SERVER_ENDPOINTS) {
    const key = endpointKey(e);
    const callers = [...new Set(callersFor(key))];
    lines.push(`| ${e.verb} | \`${normaliseServerPath(e.path)}\`${e.deprecated ? ' **@Deprecated**' : ''}`
      + ` | ${callers.join('<br>') || '**— none —**'}`
      + ` | ${UI_REACHABLE_KEYS.has(key) ? 'yes' : '**no**'} |`);
  }
  // process.stdout directly, not console.log: vitest buffers module-level console output during
  // collection and the report never appears.
  process.stdout.write(`${lines.join('\n')}\n`);
}

describe('controller surface / hrApi.js contract — harness sanity', () => {
  // Every assertion below is trivially true against an empty extraction. These run first so a
  // digest that failed to load, or a harness that stopped driving hrApi, fails LOUDLY instead of
  // passing on zero matches. The floors are set well under today's real numbers (276 operations,
  // 261 captured calls) and far above a broken derivation's output.
  it('read a plausible surface out of the committed digest', () => {
    expect(SERVER_ENDPOINTS.length).toBeGreaterThan(250);
    expect(SERVER_KEYS.size).toBeGreaterThan(250);
  });

  it('every digest entry is a concrete /api path', () => {
    // The digest is generated, so a malformed entry means the generator broke — which would
    // otherwise surface as a pile of phantom "hrApi calls an endpoint that does not exist".
    const malformed = SERVER_ENDPOINTS.filter((e) => !e.path.startsWith('/api/'));
    expect(malformed.map((e) => e.raw), 'digest entries that are not /api paths').toEqual([]);
  });

  it('the digest carries the @Deprecated subset the backend publishes', () => {
    // V141 (#702) severed three costing writes IN PLACE — still routed, still the same verb and
    // path, throwing 409. A surface comparison cannot see that; only this list can, and
    // CALLS_DEPRECATED below is what reads it. If it ever came back empty the deprecated-call
    // assertion would pass while every severed route went unwatched.
    expect(DEPRECATED_KEYS.size).toBeGreaterThan(0);
    for (const key of DEPRECATED_KEYS) expect(SERVER_KEYS).toContain(key);
  });

  it('drove every hrApi method to an observable request', () => {
    // The client-side anti-vacuity check. A method this harness cannot call — a new argument shape
    // none of ARGUMENT_PROFILES satisfies — would otherwise drop silently out of the comparison,
    // and its endpoint would look uncalled while its call went unchecked.
    expect(UNPROBED_METHODS, 'hrApi methods that issued no request under any argument profile')
      .toEqual([]);
    expect(CLIENT_CALLS.length).toBeGreaterThan(200);
  });
});

describe('controller surface / hrApi.js contract', () => {
  // ── THE DIRECTION THAT MATTERS MOST ────────────────────────────────────────
  it('hrApi calls no endpoint the backend does not serve', () => {
    const broken = [];
    for (const call of CLIENT_CALLS) {
      const key = clientKey(call);
      if (SERVER_KEYS.has(key)) continue;
      const otherVerbs = [...SERVER_KEYS]
        .filter((k) => k.endsWith(` ${call.path}`))
        .map((k) => k.split(' ')[0]);
      broken.push(
        `${call.namespace}.${call.name} → ${key}`
        + (otherVerbs.length ? ` (the path exists server-side under ${otherVerbs.join(', ')})` : ''),
      );
    }
    // No allowlist, by design: a client call with no endpoint behind it is already a 404 in
    // production. The "path exists under another verb" hint is there because a verb mismatch is
    // the likeliest cause and the least obvious from the path alone.
    expect([...new Set(broken)].sort()).toEqual([]);
  });

  // ── THE REPORTING DIRECTION ────────────────────────────────────────────────
  it('every endpoint is either called by hrApi or documented in SERVER_ONLY', () => {
    const undocumented = [...SERVER_KEYS]
      .filter((key) => !CLIENT_KEYS.has(key) && !SERVER_ONLY[key])
      .sort();
    expect(
      undocumented,
      'endpoints with no hrApi caller and no SERVER_ONLY entry. If a UI was meant to call it, wire '
      + 'it up; if it is reached by something else (a script, the scanner agents, e2e) or is a '
      + 'capability awaiting its UI, add an entry saying which. Do NOT delete a server endpoint to '
      + 'silence this.',
    ).toEqual([]);
  });

  // ── A CALL THAT MATCHES ON PATH AND VERB AND STILL ALWAYS FAILS ───────────
  //
  // HOW AN ALWAYS-409 ENDPOINT IS CLASSIFIED HERE, stated because getting it wrong both ways is
  // easy. A severed route is NOT missing: it is still routed, so the two tests above see a normal
  // match and report nothing. That is correct — answering 409 with a clear message is a deliberate
  // design in this repo, chosen precisely so a stale caller gets an explanation instead of a 404,
  // and flagging it as a broken call would be a false positive on an intentional pattern.
  //
  // Note the repo has TWO retirement shapes and only one of them lands here:
  //   • route DELETED, service method kept @Deprecated — TicketService#submit/#pickup. No mapping
  //     exists, so these never enter the comparison at all. Nothing to report.
  //   • route KEPT and severed — the three V141 costing writes below. These do enter it.
  //
  // So this test asks the narrower question the other two cannot: is a live hrApi method pointed at
  // a route the backend has already severed? That is not a false positive and not a design choice
  // — it is an unfinished migration, and it is invisible under VITE_USE_MOCKS=true because mockApi
  // never learned the route was severed.
  it('no hrApi method calls a @Deprecated endpoint beyond the documented migration', () => {
    const calling = [...new Set(
      CLIENT_CALLS
        .filter((call) => DEPRECATED_KEYS.has(clientKey(call)))
        .map((call) => `${call.namespace}.${call.name} → ${clientKey(call)}`),
    )].sort();
    const documented = calling.filter((entry) => CALLS_DEPRECATED[entry.split(' → ')[1]]);
    expect(
      calling.filter((entry) => !documented.includes(entry)),
      'hrApi calls a route the backend marked @Deprecated. These match on path and verb, so the '
      + 'contract tests above pass while every one of these calls fails at runtime.',
    ).toEqual([]);
  });

  it('every CALLS_DEPRECATED entry is still deprecated and still called', () => {
    // Self-verifying, and it doubles as the anti-vacuity check on the @Deprecated parse: if
    // isDeprecatedAt() stopped matching, DEPRECATED_KEYS would empty and these assertions fail.
    for (const [key, reason] of Object.entries(CALLS_DEPRECATED)) {
      expect(SERVER_KEYS.has(key), `CALLS_DEPRECATED lists "${key}", which no controller serves`).toBe(true);
      expect(
        DEPRECATED_KEYS.has(key),
        `CALLS_DEPRECATED["${key}"] is no longer @Deprecated — delete the entry`,
      ).toBe(true);
      expect(
        CLIENT_KEYS.has(key),
        `CALLS_DEPRECATED["${key}"] is no longer called by hrApi — the migration finished, delete the entry`,
      ).toBe(true);
      expect(reason.length, `CALLS_DEPRECATED["${key}"] needs a reason`).toBeGreaterThan(20);
    }
  });

  it('every SERVER_ONLY entry is a real, still-uncalled endpoint with a written reason', () => {
    for (const [key, reason] of Object.entries(SERVER_ONLY)) {
      expect(SERVER_KEYS.has(key), `SERVER_ONLY lists "${key}", which no controller serves`).toBe(true);
      // Stale entries rot: once hrApi starts calling an endpoint, its exemption must go, or the
      // next time that endpoint disappears server-side nothing notices.
      expect(
        CLIENT_KEYS.has(key),
        `SERVER_ONLY["${key}"] is now called by hrApi — delete the entry`,
      ).toBe(false);
      expect(reason.length, `SERVER_ONLY["${key}"] needs a reason`).toBeGreaterThan(20);
    }
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Direction 3 — is the endpoint reachable from a SCREEN?
// ─────────────────────────────────────────────────────────────────────────────


/**
 * Endpoints an hrApi method reaches, but which NO SCREEN can reach — the method is declared and
 * never called.
 *
 * ⛔ THIS IS NOT A DELETION LIST, and unlike SERVER_ONLY above these entries are NOT individually
 * researched. Every one is a MEASUREMENT: `componentCalledMethods()` found no
 * `api.<namespace>.<method>(` for the method that reaches it, anywhere outside `src/api/` and
 * outside tests. That is evidence the UI cannot reach it. It is NOT evidence the capability is
 * dead, and several here are near-certainly live-by-other-means or half-finished features —
 * the whole `deduction-obligations` cluster is the frontend half of closed issue #373, and
 * `price-import` is a five-endpoint upload flow.
 *
 * Verifying them one by one is issue #746's umbrella, which opens with its own "this is not a
 * deletion list" warning and records that only twelve of the client-side methods have been
 * hand-checked. Nothing should be removed on the strength of this list alone. This repo has been
 * wrong in BOTH directions in a single week: `CommissionStatus.VOID` looked dead and is
 * deliberately unreachable, and `cancelOpenForPricingRequest` looked like a missing capability and
 * was a verbatim duplicate of live inlined SQL.
 *
 * What the list IS for: freezing the set so it cannot grow silently. A NEW entry means a screen
 * stopped calling something, or an endpoint shipped behind a method nothing invokes — either way a
 * capability just became unreachable, and that should require a decision rather than a shrug.
 * Shrinking it (wiring a screen up, or retiring the endpoint) is the direction of travel and the
 * stale-entry test below deletes the entry for you.
 */
const UNREACHABLE_FROM_UI = new Set([
  'DELETE /api/factory-quote-attachments/{}',
  'GET /api/catalog',
  'GET /api/customer-quotations/{}',
  'GET /api/deposit-notices/{}',
  'GET /api/factory-configs',
  'GET /api/factory-quotes/{}',
  // 'GET /api/leave/policy-document' left this list on 2026-08-14: LeavePolicyDocumentPage.jsx
  // calls policyDocumentAvailable (the HEAD probe the GET mapping answers) and
  // downloadPolicyDocument, so a screen reaches it again for the first time since the reader bar
  // switched to the bundled PDF.
  'GET /api/leave/review-summary',
  'GET /api/payroll/deduction-obligations',
  'GET /api/payroll/deduction-obligations/me',
  'GET /api/payroll/deduction-obligations/{}/progress',
  'GET /api/payroll/ytd-seed',
  'GET /api/price-import/profile/{}',
  'GET /api/price-import/staging/{}',
  'GET /api/pricing-costings/{}',
  'GET /api/pricing-decisions/{}',
  'PATCH /api/profile-requests/{}',
  'POST /api/attendance/cards/backfill',
  'POST /api/commissions',
  'POST /api/customer-quotations/{}/preview',
  'POST /api/factory-quotes/{}/not-available',
  'POST /api/payroll/deduction-obligations',
  'POST /api/payroll/deduction-obligations/{}/acknowledge-completion',
  'POST /api/payroll/deduction-obligations/{}/clear-override',
  'POST /api/payroll/deduction-obligations/{}/override-continue',
  'POST /api/payroll/deduction-obligations/{}/stop',
  'POST /api/payroll/tax-allowances/declarations/me/estimate',
  'POST /api/price-import/commit/{}',
  'POST /api/price-import/upload',
  'POST /api/price-import/validate/{}',
  // The three V141-severed costing writes. These arrived here on 2026-08-14 by DELETION, not by
  // drift: #747's four controls were the only screen call sites and the owner ruled them out. They
  // are also the three CALLS_DEPRECATED entries — see that block for why hrApi still declares them
  // (mockApi.depositNotices.test.js needs the chain until the mock learns markReadyForCosting's
  // auto-advance) and why that is a separate change from this one.
  'POST /api/pricing-costings/{}/recalculate',
  'POST /api/pricing-costings/{}/submit',
  'POST /api/pricing-requests/{}/costings',
  // 'POST /api/tickets/{}/entry-channel' was here until issue #740 wired DealStagePanel's
  // ช่องทางรับงาน control. The `UNREACHABLE_FROM_UI entry is real and still unreachable` test is
  // what demanded this deletion — it is not an optional tidy-up.
  'POST /api/tickets/{}/factory-emails/send',
  'PUT /api/payroll/deduction-obligations/{}',
  'PUT /api/payroll/tax-allowances',
  'PUT /api/payroll/ytd-seed',
  'PUT /api/price-import/profile/{}',
]);

describe('controller surface / hrApi.js contract — UI reachability', () => {
  it('drove the UI scan to a plausible result', () => {
    // Anti-vacuity, same shape as the harness-sanity block. If the scan matched nothing —
    // a moved src tree, a changed call idiom — every endpoint would look unreachable and the
    // allowlist below would silently become the whole surface.
    expect(UI_CALLED_METHODS.size).toBeGreaterThan(150);
    expect(UI_REACHABLE_KEYS.size).toBeGreaterThan(150);
  });

  it('every endpoint a screen cannot reach is a known one', () => {
    const newlyUnreachable = [...SERVER_KEYS]
      .filter((key) => CLIENT_KEYS.has(key))
      .filter((key) => !UI_REACHABLE_KEYS.has(key))
      .filter((key) => !UNREACHABLE_FROM_UI.has(key))
      .sort();

    expect(
      newlyUnreachable,
      'endpoints whose only hrApi caller is a method no screen invokes. Either wire up the screen, '
      + 'or add the endpoint to UNREACHABLE_FROM_UI — deliberately, and read that block first',
    ).toEqual([]);
  });

  it('every UNREACHABLE_FROM_UI entry is real and still unreachable', () => {
    const stale = [];
    for (const key of UNREACHABLE_FROM_UI) {
      if (!SERVER_KEYS.has(key)) stale.push(`${key} — no longer served; drop this entry`);
      else if (UI_REACHABLE_KEYS.has(key)) stale.push(`${key} — a screen now calls it; drop this entry`);
    }
    // Without this the list rots into an excuse for endpoints someone already fixed, and the
    // count stops meaning anything.
    expect(stale).toEqual([]);
  });

  it('the published reachable set matches what the scan computes', () => {
    // docs/api/ui-reachable.json is consumed by the backend's ResponseFieldContractTest (#727) to
    // stop pinning response fields on schemas no screen can reach. Publishing it without a drift
    // guard would hand that test a stale input and quietly re-introduce the over-pin it fixes.
    //
    // Raw form, not normalised, so it intersects directly with api-surface.json.
    const reachable = SERVER_ENDPOINTS
      .filter((endpoint) => UI_REACHABLE_KEYS.has(endpoint.key))
      .map((endpoint) => endpoint.raw)
      .sort();

    if (process.env[UI_REACHABLE_UPDATE]) {
      writeUiReachable(reachable);
      return;
    }

    expect(
      reachable,
      `docs/api/ui-reachable.json is stale. Regenerate: cd frontend && ${UI_REACHABLE_UPDATE}=1 `
      + 'npx vitest run src/api/serverContract.test.js — and say so in the PR body, because '
      + "ResponseFieldContractTest's pin set derives from it",
    ).toEqual(readUiReachable());
  });

  it('no module outside src/api builds an /api/ path itself', () => {
    // A component that hand-builds a URL escapes this file, contract.test.js and the e2e sweep
    // alike — none of them can see it. Comments are stripped first: UpcomingHolidays.jsx
    // documents `/api/holidays` in prose precisely to explain that it does NOT call it.
    expect(apiPathBypasses()).toEqual([]);
  });
});
