ALTER TABLE sales.ticket ADD COLUMN has_edits BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE sales.ticket_event DROP CONSTRAINT chk_event_kind;
ALTER TABLE sales.ticket_event ADD CONSTRAINT chk_event_kind CHECK (kind IN (
    'CREATED','SUBMITTED','PICKED_UP','PRICE_PROPOSED',
    'APPROVED','REJECTED','QUOTATION_ISSUED',
    'COMMENTED','CLOSED','CANCELLED','EDITED'
));
