-- V173: sales.designer — read-only "ผู้ออกแบบ" (designer) directory, seeded from the owner's Excel.
--
-- ── Why ──────────────────────────────────────────────────────────────────────────────────────
-- Owner feedback (2026-09-12): when entering customer info on a quotation, add a way to pick the
-- ผู้ออกแบบ (designer) so the quotation's D.Co. field (sales.quotation.unit_code, VARCHAR(20),
-- added by V165 -- labelled "หน่วยงาน" in Thai / "D.Co." on the English F-SM-008) fills
-- AUTOMATICALLY with that designer's CODE. Clarified by the owner:
--   "มีใหัเลือก ผู้ออกแบบ แล้ว automaitcally ขึ้น d.co แต่ไม่ต้องขึ้นชื่อผู้ออกแบบ (เป็นความลับ)"
--   -- the designer's NAME is confidential and must NEVER reach a printed document; it exists
--   only so a sales rep can FIND the right code by name in the picker.
-- Storage/maintenance, also the owner's own words: "อ่านอย่างเดียว อัปเดตจาก Excel" -- this table
-- is READ-ONLY from the application's point of view. There are NO write endpoints anywhere in this
-- change (see DesignerController); the only way this table's contents ever change is a FUTURE
-- migration re-importing a refreshed Excel export. That is a deliberate scope limit, not an
-- oversight -- do not add a create/update/delete endpoint for this table without a fresh owner ask.
--
-- ── What this does NOT do ────────────────────────────────────────────────────────────────────
-- This does NOT touch sales.quotation.unit_code itself, its type, or anything already reading or
-- writing it (DealQuotationRenderAdapter, QuotationRenderModel, DealQuotationRepository, the XLS/
-- PDF renderer). A designer pick is purely a FRONTEND convenience that writes the same free-text
-- unit_code column a rep could always type into by hand -- see QuotationEditorPage.jsx's existing
-- "หน่วยงาน" input, which stays editable exactly as before. sales.dept_code ("ฝ่าย" / Dept.) is a
-- SEPARATE, unrelated column and is not touched here either.
--
-- ── Data ─────────────────────────────────────────────────────────────────────────────────────
-- Seeded from a 30-sheet owner Excel workbook, parsed into a clean (code, name, active,
-- source_sheet) dataset and reviewed by hand before being turned into the INSERT below:
--   * 1,115 designers total; source_sheet records which workbook tab a row came from, for
--     traceability back to the source spreadsheet on a future re-import.
--   * 13 rows were marked ยกเลิก (cancelled) in the source and are seeded with active = FALSE.
--     Owner ruling: "เก็บไว้ แต่เลือกใหม่ไม่ได้" -- KEEP them (an existing quotation may already
--     carry one of their codes in unit_code) but they must not be offered to a NEW pick. See
--     DesignerRepository.search (active-only) vs DesignerRepository.findByCode (any status).
--   * Codes are NOT one consistent shape -- 'A001', '1001', 'FL1', 'ON001', 'ก001' (Thai script)
--     are all real and all present. code is a plain VARCHAR(20) PK with no format CHECK.
--   * The owner's sheet also carried a "sales owner" nickname column (ยา/จอย/หมวย/รี่/เชอรี่).
--     Owner ruling: "ไม่ต้องเก็บ" -- deliberately NOT a column on this table and NOT in the seed.
--   * Four codes (FL23, S105, V012, V019) had two ACTIVE rows in the source workbook with
--     different names for the same code. The owner is aware and will correct the source Excel;
--     this migration keeps only the FIRST name encountered for each, so `code` can stay the
--     primary key. If the owner's correction changes which name is right, that arrives as a
--     later forward-only migration, never an edit to this one.
--
-- ── Idempotency ──────────────────────────────────────────────────────────────────────────────
-- Every row is an anti-join on the natural key (code), same convention as V91.1's bulk seed --
-- running this migration twice (impossible under normal Flyway operation, but this is the shape
-- the repo already uses for "large seed" migrations) inserts nothing the second time.
--
-- ── 🚨 OWNER APPROVAL — READ BEFORE DEPLOYING ───────────────────────────────────────────────
-- This migration has NOT been shown to the owner yet. V171/V172 were approved; this one is not.
-- Per CLAUDE.md, a migration reaching production is an owner-approved operation with a rollback
-- plan. Do not build+push a backend image or bump render.yaml's pinned tag for this until the
-- owner has seen and approved this exact file.
--
-- ── Rollback plan ────────────────────────────────────────────────────────────────────────────
-- This migration is purely additive (one new table, no ALTER of any existing table, no column on
-- sales.quotation touched). If it needs to be undone after deploying:
--   1. Confirm no other migration has been layered on top of sales.designer in the meantime
--      (`SELECT version FROM hr.flyway_schema_history WHERE version::numeric > 173`).
--   2. Run manually, NOT as a new migration file (this is a hand-run DBA rollback, since Flyway
--      migrations are forward-only and this file itself must never be edited or renumbered):
--           DROP TABLE IF EXISTS sales.designer;
--      There is no FK from sales.quotation (or anywhere else) to sales.designer -- unit_code has
--      always been, and remains, a free-text column -- so dropping this table cannot orphan or
--      cascade into any other row anywhere in the schema.
--   3. Remove the row for V173 from hr.flyway_schema_history so a future re-add of this feature
--      does not collide with Flyway's applied-migration bookkeeping:
--           DELETE FROM hr.flyway_schema_history WHERE version = '173';
--   4. On the frontend, VITE build simply stops calling GET /api/designers*; those endpoints
--      404ing is the only user-visible effect, and the "หน่วยงาน" input keeps working exactly as
--      it does today because it was never dependent on this table to begin with.

CREATE TABLE sales.designer (
    code          VARCHAR(20)  PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Which tab of the owner's Excel workbook this row came from — traceability for the next
    -- re-import, nothing more; not surfaced anywhere in the API or UI.
    source_sheet  VARCHAR(20),
    imported_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE sales.designer IS
    'ผู้ออกแบบ (designer) directory. READ-ONLY from the app -- refreshed only by re-running a '
    'future import migration against a refreshed Excel export. name is CONFIDENTIAL and must '
    'never reach a rendered quotation; only code is ever written into sales.quotation.unit_code.';
COMMENT ON COLUMN sales.designer.active IS
    'FALSE = ยกเลิก in the source workbook. Kept (an existing quotation may reference the code) '
    'but excluded from DesignerRepository.search so it cannot be picked for a NEW quotation.';

-- Sales reps look designers up by code OR by name (they usually know the name, the document needs
-- the code) -- index both. name has no case-insensitive index because the ~1,100-row table is
-- small enough that a plain ILIKE seq scan is not worth a functional/trigram index for now.
CREATE INDEX idx_designer_active ON sales.designer(active);

INSERT INTO sales.designer (code, name, active, source_sheet)
SELECT v.code, v.name, v.active, v.source_sheet
  FROM (VALUES
    ('1001', '195 ARCHITECH', TRUE, 'ตัวเลข'),
    ('1002', '1819 LANDSCAPE', TRUE, 'ตัวเลข'),
    ('1003', '99 DD', TRUE, 'ตัวเลข'),
    ('1004', '21 DESIGN', TRUE, 'ตัวเลข'),
    ('1005', '3045 STUDIO', TRUE, 'ตัวเลข'),
    ('1006', '2D PLUS', TRUE, 'ตัวเลข'),
    ('1007', '3 PLUS 1', TRUE, 'ตัวเลข'),
    ('1008', '3C INTERIOR', TRUE, 'ตัวเลข'),
    ('1009', '27 ARCHTECT', TRUE, 'ตัวเลข'),
    ('1010', '3D INTERIOR', TRUE, 'ตัวเลข'),
    ('1011', '3BS', TRUE, 'ตัวเลข'),
    ('1012', '23 ID', TRUE, 'ตัวเลข'),
    ('1013', '18 DESIGN', TRUE, 'ตัวเลข'),
    ('1014', '250', TRUE, 'ตัวเลข'),
    ('1015', '71 DESIGN', TRUE, 'ตัวเลข'),
    ('1016', '760 I ARCHITECT', TRUE, 'ตัวเลข'),
    ('1017', '11 เมษา', TRUE, 'ตัวเลข'),
    ('1018', '24 Design Studio บ้านคุณศสิดารา', TRUE, 'ตัวเลข'),
    ('1019', '10 Design', TRUE, 'ตัวเลข'),
    ('1020', '2605 Design Develop Definition', TRUE, 'ตัวเลข'),
    ('1021', '369 House Design', TRUE, 'ตัวเลข'),
    ('1022', '56 Design Studio', TRUE, 'ตัวเลข'),
    ('1023', '10DK', TRUE, 'ตัวเลข'),
    ('1024', '191 Interior Design', TRUE, 'ตัวเลข'),
    ('1025', '10 Space Architect', TRUE, 'ตัวเลข'),
    ('1026', '67''s', TRUE, 'ตัวเลข'),
    ('1027', '32interiors', TRUE, 'ตัวเลข'),
    ('A001', 'ABACUS DESIGN CO.,LTD', TRUE, 'A'),
    ('A002', 'ARDEC', TRUE, 'A'),
    ('A003', 'APIS CO.,LTD', TRUE, 'A'),
    ('A004', 'AGORA DESIGN MAT', TRUE, 'A'),
    ('A005', 'แอมมัสซี่', TRUE, 'A'),
    ('A006', 'ASC INTERIORS CO.,LTD', TRUE, 'A'),
    ('A007', 'แอตเซคิด', TRUE, 'A'),
    ('A008', 'ABOUT SPACE', TRUE, 'A'),
    ('A009', 'เอเดค', TRUE, 'A'),
    ('A010', 'AI DESIGN', TRUE, 'A'),
    ('A011', 'AUGUST DESIGN', TRUE, 'A'),
    ('A012', 'A.A.D ARCHITECH', TRUE, 'A'),
    ('A013', 'ATTA', TRUE, 'A'),
    ('A014', 'AMAZE INTOR', TRUE, 'A'),
    ('A015', 'AMAZE', TRUE, 'A'),
    ('A016', 'ANUPAP ONSARD DESIGN', TRUE, 'A'),
    ('A017', 'ALICIA', TRUE, 'A'),
    ('A018', 'AFSG, HONG KONG', TRUE, 'A'),
    ('A019', 'AGUA HOUSES CO.LTD (มั่วชื่อ)', TRUE, 'A'),
    ('A020', 'AB STRACT', TRUE, 'A'),
    ('A021', 'ASIAN MOTIF', TRUE, 'A'),
    ('A022', 'A49', TRUE, 'A'),
    ('A023', 'ASPGKTE DESIGN', TRUE, 'A'),
    ('A024', 'AMA', TRUE, 'A'),
    ('A025', 'ARBAY', TRUE, 'A'),
    ('A026', 'ARCHITECT KIDD', TRUE, 'A'),
    ('A027', 'อาคิเทค', TRUE, 'A'),
    ('A028', 'อาร์คิเทคเจอร์ อินทีเรีย', TRUE, 'A'),
    ('A029', 'ASIA SPACE', TRUE, 'A'),
    ('A030', 'ARDEG', TRUE, 'A'),
    ('A031', 'ARCHITECTURAL CO.,LTD', TRUE, 'A'),
    ('A032', 'AXIS LANDSCAPE', TRUE, 'A'),
    ('A033', 'ARCHITECTURE INIORIOR', TRUE, 'A'),
    ('A034', 'ARCHER ARCHITECT', TRUE, 'A'),
    ('A035', 'AP''STRACT', TRUE, 'A'),
    ('A036', 'A.B.C. DESIGN', TRUE, 'A'),
    ('A037', 'AMIDU', TRUE, 'A'),
    ('A038', 'ASIA SPACE', TRUE, 'A'),
    ('A039', 'APLUS', TRUE, 'A'),
    ('A040', 'ABADE DEVELOPMENT', TRUE, 'A'),
    ('A041', 'AUSPICE', TRUE, 'A'),
    ('A042', 'ARCHITECT GO GRAP', TRUE, 'A'),
    ('A043', 'AESTHETICS ARCHITECTS', TRUE, 'A'),
    ('A044', 'ACM_DESIGN', TRUE, 'A'),
    ('A045', 'ATELIERCF ARCHITECTS', TRUE, 'A'),
    ('A046', 'ANONY MAS', TRUE, 'A'),
    ('A047', 'AVROKO', TRUE, 'A'),
    ('A048', 'ALEXANDER WATER WATH', TRUE, 'A'),
    ('A049', 'ARTI DESIGN', FALSE, 'A'),
    ('A050', 'ARCHIPLAN', TRUE, 'A'),
    ('A051', 'ATELIER OF ARCHITECTS', TRUE, 'A'),
    ('A052', 'APATMENT INTERIOR', TRUE, 'A'),
    ('A053', 'AREEYA', TRUE, 'A'),
    ('A054', 'ARMANIA GROP', TRUE, 'A'),
    ('A055', 'ANONY MAS', TRUE, 'A'),
    ('A056', 'ARCHITRAVE DESIGN&PLANING', TRUE, 'A'),
    ('A057', 'A&S', TRUE, 'A'),
    ('A058', 'ATAM DESIGN', TRUE, 'A'),
    ('A059', 'AGORA DESIGN MAT', FALSE, 'A'),
    ('A060', 'ABACUS DESIGN CO.,LTD', FALSE, 'A'),
    ('A061', 'AESTHETIC', TRUE, 'A'),
    ('A062', 'A PLUS S', TRUE, 'A'),
    ('A063', 'A PLUS CAN', TRUE, 'A'),
    ('A064', 'A49HD', TRUE, 'A'),
    ('A065', 'ARCHITECT''S GALLERY', TRUE, 'A'),
    ('A066', 'ARCHITECT 3D', TRUE, 'A'),
    ('A067', 'AOMO', TRUE, 'A'),
    ('A068', 'ALL ZONE DESIGN', TRUE, 'A'),
    ('A069', 'ARCHGANG', TRUE, 'A'),
    ('A070', 'A&A', TRUE, 'A'),
    ('A071', 'AXIS', TRUE, 'A'),
    ('A072', 'A PLUS L', TRUE, 'A'),
    ('A073', 'ALKHEMIST ARCHITECTS', TRUE, 'A'),
    ('A074', 'ATOM', TRUE, 'A'),
    ('A075', 'ALGO', TRUE, 'A'),
    ('A076', 'ARCHITYPE', TRUE, 'A'),
    ('A077', 'ATERIAR PONG', TRUE, 'A'),
    ('A078', 'บ.อรุณแสงชัย (ACS DESIGN)', TRUE, 'A'),
    ('A079', 'Artra Interior', TRUE, 'A'),
    ('A080', 'ASE ARCHITECTURE STPATEGY STPATEGY ENVIRONMENT', TRUE, 'A'),
    ('A081', 'ARTI ARCHITECT', TRUE, 'A'),
    ('A082', 'Artisine Studio', TRUE, 'A'),
    ('A083', 'Architect Area', TRUE, 'A'),
    ('A084', 'OBA', TRUE, 'A'),
    ('A085', 'AOK (Studio ACT of Kindness)', TRUE, 'A'),
    ('A086', 'Airspace Architect', TRUE, 'A'),
    ('A087', 'Alkoven', TRUE, 'A'),
    ('A088', 'AMASS', TRUE, 'A'),
    ('A089', 'Aim Interior Design', TRUE, 'A'),
    ('A090', 'อาร์คิเทค บีเคเค (บริษัทเดียวกับไอเดียไอแคน) Atchitect BKK', TRUE, 'A'),
    ('A091', 'ANI DESIGN', TRUE, 'A'),
    ('A092', 'Anneal Atelier X Wide and Narrow', TRUE, 'A'),
    ('A093', 'AIRBASE', TRUE, 'A'),
    ('A094', 'Ayutt and Associates design', TRUE, 'A'),
    ('A095', 'Aviv Studio', TRUE, 'A'),
    ('A096', 'ALT ARCHITECTS (FB : 24/4)', TRUE, 'A'),
    ('A097', 'ARCH+BRAND Design A+B', TRUE, 'A'),
    ('A098', 'AOT Design', TRUE, 'A'),
    ('A099', 'Archive Studio', TRUE, 'A'),
    ('A100', 'A01', TRUE, 'A'),
    ('A101', 'aim immagenalist', TRUE, 'A'),
    ('A102', 'Akas Architects (FB)', TRUE, 'A'),
    ('A103', 'Approx (Appropriate Times Ten)', TRUE, 'A'),
    ('A104', 'Ajin Studio', TRUE, 'A'),
    ('A105', 'ATELIER 8', TRUE, 'A'),
    ('A106', 'AIM - aim Imaginarists', TRUE, 'A'),
    ('A107', 'ADD Design Studio', TRUE, 'A'),
    ('A108', 'AA+A', TRUE, 'A'),
    ('A109', 'A49 เชียงใหม่', TRUE, 'A'),
    ('A110', 'A D/M', TRUE, 'A'),
    ('A111', 'Abalance Interior', TRUE, 'A'),
    ('A112', 'Aca Interior', TRUE, 'A'),
    ('A113', 'Arch+Brand Design', TRUE, 'A'),
    ('A114', 'ASWA Architech', TRUE, 'A'),
    ('A115', 'ANOTHER', TRUE, 'A'),
    ('A116', 'AD Deco Built In & Design Co.,Ltd. (Line OA)', TRUE, 'A'),
    ('B001', 'BUNNAG ARCHITECTS', TRUE, 'B'),
    ('B002', 'BENSLEY', TRUE, 'B'),
    ('B003', 'B/A/R', TRUE, 'B'),
    ('B004', 'BGNT SEVERIN', TRUE, 'B'),
    ('B005', 'BE GREY', TRUE, 'B'),
    ('B006', 'บางกอก อาร์เต็ก', TRUE, 'B'),
    ('B007', 'บัลด์ อินเตอร์', TRUE, 'B'),
    ('B008', 'BALANCING ACT', TRUE, 'B'),
    ('B009', 'BROWE HOUSE', FALSE, 'B'),
    ('B010', 'บางกอก เดย์กรุ๊ป', FALSE, 'B'),
    ('B011', 'BANGKOK UNDERGROUND', TRUE, 'B'),
    ('B012', 'BUG STUDIO', TRUE, 'B'),
    ('B013', 'BCM', TRUE, 'B'),
    ('B014', 'BLINK DESIGN GROUP', TRUE, 'B'),
    ('B015', 'BCNA INTERNATIONAL', TRUE, 'B'),
    ('B016', 'BHUMIDHOP', TRUE, 'B'),
    ('B017', 'BRERMUDO LANDSCAPE', TRUE, 'B'),
    ('B018', 'BEAUMONT ARCHITECTURE', TRUE, 'B'),
    ('B019', 'BELICOLLINS', TRUE, 'B'),
    ('B020', 'BOON DESIGN', TRUE, 'B'),
    ('B021', 'โบสห์ ทรี', TRUE, 'B'),
    ('B022', 'BANGKOK DAY', TRUE, 'B'),
    ('B023', 'BREATH', TRUE, 'B'),
    ('B024', 'BROWN HOUSE', TRUE, 'B'),
    ('B025', 'BAE', TRUE, 'B'),
    ('B026', 'คิดดี', TRUE, 'B'),
    ('B027', 'BEAUMONT ARCHITECTURE', FALSE, 'B'),
    ('B028', 'BUG STUDIO', FALSE, 'B'),
    ('B029', 'BLACK PENICIL', TRUE, 'B'),
    ('B030', 'Beourfriend', TRUE, 'B'),
    ('B031', 'Bellman Design Studio', TRUE, 'B'),
    ('B032', 'B+W Design Studio', TRUE, 'B'),
    ('B033', 'BWR Render (Online)', TRUE, 'B'),
    ('B034', 'B-Khai', TRUE, 'B'),
    ('B035', 'BORIBOONDESIGNSTUDIO CO., LTD.', TRUE, 'B'),
    ('B036', 'BRIT STUDIO CO., LTD /บริชญ์ สตูดิโอ จำกัด', TRUE, 'B'),
    ('B037', 'Brave Architect', TRUE, 'B'),
    ('B038', 'BEHOLD', TRUE, 'B'),
    ('B039', 'Blackbean Design & Construction', TRUE, 'B'),
    ('B040', 'Blanc Interioe Design Studio', TRUE, 'B'),
    ('B041', 'BLANK Studio (มาทางOA พี่ออยส่งให้ 1/4/25)', TRUE, 'B'),
    ('B042', 'BBAW (ในเครือ IAW)', TRUE, 'B'),
    ('B043', 'Bodinchapa Architects', TRUE, 'B'),
    ('B044', 'BORIBOT STUDIO CO., LTD', TRUE, 'B'),
    ('C001', 'คิวบิค', TRUE, 'C'),
    ('C002', 'คิวด้า', TRUE, 'C'),
    ('C003', 'CHABA A DESIGN', TRUE, 'C'),
    ('C004', 'ครี-พลู', TRUE, 'C'),
    ('C006', 'คริสเตียนี่', TRUE, 'C'),
    ('C010', 'CM72', TRUE, 'C'),
    ('C011', 'CITY SPATE', TRUE, 'C'),
    ('C015', 'C2 STUDIO', TRUE, 'C'),
    ('C016', 'Create Great Design Co.,Ltd (CGD)', TRUE, 'C'),
    ('C017', 'CHINA GROUP', TRUE, 'C'),
    ('C018', 'CHEMISTRI', TRUE, 'C'),
    ('C019', 'CBR', TRUE, 'C'),
    ('C020', 'CL3', TRUE, 'C'),
    ('C021', 'CONCGIT I', TRUE, 'C'),
    ('C022', 'CRISIMA SA NITARY', TRUE, 'C'),
    ('C023', 'CHIMA DESIGN', TRUE, 'C'),
    ('C024', 'COMBIMATION', TRUE, 'C'),
    ('C026', 'C&C WORSLIOP', TRUE, 'C'),
    ('C027', 'CORNGRCAT', TRUE, 'C'),
    ('C028', 'CHIC 39 B PLUS B', TRUE, 'C'),
    ('C029', 'CONTOUR', TRUE, 'C'),
    ('C030', 'CANCU STUDIO', TRUE, 'C'),
    ('C031', 'CHAPMAM TAYLA', TRUE, 'C'),
    ('C032', 'CHALEEYA DESIGN', TRUE, 'C'),
    ('C033', 'CHARCEN Décor', TRUE, 'C'),
    ('C034', 'CHIMPANZEE DESIGN', TRUE, 'C'),
    ('C035', 'CRH', TRUE, 'C'),
    ('C036', 'CHAT ARCHITECT', TRUE, 'C'),
    ('C037', 'COQUO STUDIO', TRUE, 'C'),
    ('C038', 'CHANAWIN SOONTARNYSIPT', TRUE, 'C'),
    ('C039', 'Chorbeth@Co', TRUE, 'C'),
    ('C040', 'Collab T Design', TRUE, 'C'),
    ('C041', 'CO-Temporary', TRUE, 'C'),
    ('C042', 'Commonspace Architect', TRUE, 'C'),
    ('C043', 'CUBIC SPACE', TRUE, 'C'),
    ('C051', 'CAAM Architect', TRUE, 'C'),
    ('C052', 'Creative Territories', TRUE, 'C'),
    ('C053', 'CODESPACE ARCHITECT', TRUE, 'C'),
    ('C054', 'Chapman Taylor', TRUE, 'C'),
    ('C055', 'Cher-Wad', TRUE, 'C'),
    ('C056', 'CODE STUDIO', TRUE, 'C'),
    ('C057', 'Cana Architects', TRUE, 'C'),
    ('C058', 'Charrette Studio', TRUE, 'C'),
    ('C059', 'CTR Design Studio', TRUE, 'C'),
    ('C060', 'Central', TRUE, 'C'),
    ('C061', 'CHAN STUDIO﻿', TRUE, 'C'),
    ('C062', 'CONSULTING AND MANAGEMENT 49 LIMITED / CM49', TRUE, 'C'),
    ('C063', 'Chanint', TRUE, 'C'),
    ('C064', 'Charcoal Design Co.,Ltd.', TRUE, 'C'),
    ('C065', 'CCW', TRUE, 'C'),
    ('D001', 'ดีไซน์ ซีน Design scene', TRUE, 'D'),
    ('D002', 'ดวงฤทธิ์ บุญนาค (DBAL)', TRUE, 'D'),
    ('D003', 'ดีไซน์ทีด', TRUE, 'D'),
    ('D004', 'DT GROUP', TRUE, 'D'),
    ('D005', 'ดีไซน์ ไลท์ เซฟเวอร์', TRUE, 'D'),
    ('D006', 'ดีไซน์โปรไฟล์', TRUE, 'D'),
    ('D007', 'ดีไซน์เดบู / DESIGN T2', TRUE, 'D'),
    ('D008', 'ดีพีด', TRUE, 'D'),
    ('D009', 'Deca', TRUE, 'D'),
    ('D010', 'ดีไซน์เนอร์กาย', TRUE, 'D'),
    ('D011', 'DI DESIGN', TRUE, 'D'),
    ('D012', 'D.S.C TRADING', TRUE, 'D'),
    ('D013', 'DESIGN S07', TRUE, 'D'),
    ('D014', 'ดิ อินทีเรีย ดรัต', TRUE, 'D'),
    ('D015', 'D PLUS CRAFT', TRUE, 'D'),
    ('D016', 'DIFF I', TRUE, 'D'),
    ('D017', '18 DESIGN (ใช้รหัส 1013 แทน)', TRUE, 'D'),
    ('D018', 'เดคคอร์มาร์ท', TRUE, 'D'),
    ('D019', 'OLEE', TRUE, 'D'),
    ('D020', 'DWP CITYSPACE', TRUE, 'D'),
    ('D021', 'DIU', TRUE, 'D'),
    ('D022', 'DG HUB', TRUE, 'D'),
    ('D023', 'DILIFE SAVER', TRUE, 'D'),
    ('D024', 'DESIGN S', TRUE, 'D'),
    ('D025', 'DESIGN M&A', TRUE, 'D'),
    ('D026', 'DESIGN DEFINITION', TRUE, 'D'),
    ('D027', 'DESIGN I.KETEC', TRUE, 'D'),
    ('D028', 'ดีไซน์ ซอร์ส', TRUE, 'D'),
    ('D029', 'DESIGN THAILAND', TRUE, 'D'),
    ('D030', 'DESIGN DEFINITION', TRUE, 'D'),
    ('D031', 'DOT2LINE', TRUE, 'D'),
    ('D032', 'DESIGN DEVELOP', TRUE, 'D'),
    ('D033', 'DAC', TRUE, 'D'),
    ('D034', 'DESIGN FORWARD', TRUE, 'D'),
    ('D035', 'DELL ROBBIA', TRUE, 'D'),
    ('D036', 'DESIGN CONCEPT', TRUE, 'D'),
    ('D037', 'DELINEARCHITECTS', TRUE, 'D'),
    ('D038', 'D SPACE', TRUE, 'D'),
    ('D039', 'Design In Motiontion DIM', TRUE, 'D'),
    ('D040', 'DEPARTMENT OF ARCHITECTURE', TRUE, 'D'),
    ('D041', 'DESIGN QUA', TRUE, 'D'),
    ('D042', 'DAF&TBT', TRUE, 'D'),
    ('D044', 'ดีบี สตูดิโอ', TRUE, 'D'),
    ('D045', 'DESIGN T2', TRUE, 'D'),
    ('D046', 'ดิน สตูดิโอ Din Studio Dimenstional interpretation', TRUE, 'D'),
    ('D047', 'Double V', TRUE, 'D'),
    ('D048', 'Depict', TRUE, 'D'),
    ('D049', 'Design Motif', TRUE, 'D'),
    ('D050', 'DOT interior Studio', TRUE, 'D'),
    ('D051', 'DOTTIF.Interior', TRUE, 'D'),
    ('D052', 'D Crafters', TRUE, 'D'),
    ('D053', 'DNA', TRUE, 'D'),
    ('D054', 'DIB BANGKOK A PLACE OF ART', TRUE, 'D'),
    ('D055', 'DUDE DESIGN STUDIO', TRUE, 'D'),
    ('D056', 'Design in Vitro (DIV)', TRUE, 'D'),
    ('D057', 'Dishes', TRUE, 'D'),
    ('D058', 'D CUBIC DESIGN & SPACE', TRUE, 'D'),
    ('D059', 'Quad&Co / DTU_Design to the universe', TRUE, 'D'),
    ('D060', 'Dot 2 Line', TRUE, 'D'),
    ('D061', 'decor studio', TRUE, 'D'),
    ('D062', 'DEKOR STUDIO', TRUE, 'D'),
    ('D063', 'DT Design', TRUE, 'D'),
    ('D064', 'DP Architected', TRUE, 'D'),
    ('D065', 'Dot Line Plan', TRUE, 'D'),
    ('D066', 'designbyPATA', TRUE, 'D'),
    ('D067', 'Drafting and Steel', TRUE, 'D'),
    ('E001', 'EMBASSY', TRUE, 'E'),
    ('E002', 'ECO-ID ARCHITECTS', TRUE, 'E'),
    ('E003', 'ELE', TRUE, 'E'),
    ('E004', 'EIGHTSIXTHREE', TRUE, 'E'),
    ('E005', 'EHL DESIGN', TRUE, 'E'),
    ('E006', '18 DESIGN (ใช้รหัส 1013 แทน)', TRUE, 'E'),
    ('E007', 'ELEMENT DESIGN', TRUE, 'E'),
    ('E008', 'EMPERAR D1', TRUE, 'E'),
    ('E009', 'ELEVACAN STUDIO', TRUE, 'E'),
    ('E010', 'EXTRA BIG SALES', TRUE, 'E'),
    ('E011', 'EURO CREATIONS', TRUE, 'E'),
    ('E012', 'EVERY DESIGN & CONSTRUCTION COMPANY LIMITED', TRUE, 'E'),
    ('E013', 'ELE IN EVERYDAY LIFE ELEMENIS', TRUE, 'E'),
    ('E014', 'Esteque Studio', TRUE, 'E'),
    ('E015', 'exact art studio', TRUE, 'E'),
    ('E016', 'EVERTING IS PAINTS', TRUE, 'E'),
    ('E017', 'Euro Creations', TRUE, 'E'),
    ('E018', 'Erix-design', TRUE, 'E'),
    ('F002', 'Forx', TRUE, 'F'),
    ('F004', 'FUSION ARCH', TRUE, 'F'),
    ('F005', 'FEBRUAR', TRUE, 'F'),
    ('F006', 'FEEL MORE', TRUE, 'F'),
    ('F007', 'เฟรม เวิคร์', TRUE, 'F'),
    ('F008', 'FOUR B', TRUE, 'F'),
    ('F009', 'เฟอร์นิมาร์ท อินเตอร์เนชั่นแนล', TRUE, 'F'),
    ('F010', 'FORR', TRUE, 'F'),
    ('F011', 'FOUR B ARCHITECTS', TRUE, 'F'),
    ('F012', 'Foster', TRUE, 'F'),
    ('F013', 'Flax 12', TRUE, 'F'),
    ('F014', 'Furfacto + Stodio', TRUE, 'F'),
    ('F015', 'Flix Landscape', TRUE, 'F'),
    ('F016', 'Francodesino คุณวี', TRUE, 'F'),
    ('F017', 'คุณเฟิร์ส (เดิม PIA)', TRUE, 'F'),
    ('F018', 'Fatboy', TRUE, 'F'),
    ('F019', 'FATTSTUDIO ARCHITECT CO .,LTD', TRUE, 'F'),
    ('F020', 'Framework', TRUE, 'F'),
    ('F021', 'FRACTAL STUDIO', TRUE, 'F'),
    ('F022', 'Field Lanscape', TRUE, 'F'),
    ('FL1', 'คุณปรมซ์', TRUE, 'FL'),
    ('FL10', 'คุณกอล์ฟ', TRUE, 'FL'),
    ('FL11', 'K.BOB', TRUE, 'FL'),
    ('FL12', 'คุณสรายุทธ', TRUE, 'FL'),
    ('FL13', 'คุณกัน', TRUE, 'FL'),
    ('FL14', 'คุณแจน', TRUE, 'FL'),
    ('FL15', 'คุณแตน (Soda เก่า)', TRUE, 'FL'),
    ('FL16', 'คุณครีม', TRUE, 'FL'),
    ('FL17', 'คุณพลอย เคยอยู่ DBAL', TRUE, 'FL'),
    ('FL18', 'คุณเต้', TRUE, 'FL'),
    ('FL19', 'Supatchaya Pianpayanangkul', TRUE, 'FL'),
    ('FL2', 'คุณหทัยรินทร์ อธิภูวเวโรจ์', TRUE, 'FL'),
    ('FL20', 'คุณพงศ์พณิช ชัยณรงค์ (เต้ย)', TRUE, 'FL'),
    ('FL21', 'คุณเจี๊ยบ', TRUE, 'FL'),
    ('FL22', 'คุณปลาย', TRUE, 'FL'),
    ('FL23', 'คุณเต้+คุณกัน', TRUE, 'FL'),
    ('FL24', 'คุณต๊อก', TRUE, 'FL'),
    ('FL25', 'คุณพิศณุ (คุณต่อ)', TRUE, 'FL'),
    ('FL26', 'คุณสุกัญญา ไชยวุฒิกรณ์วานิช', TRUE, 'FL'),
    ('FL27', 'คุณกฤษณ์ ไชยงามศรี (คุณแมก)', TRUE, 'FL'),
    ('FL28', 'คุณเกมส์ เคยอยู่ DBAL', TRUE, 'FL'),
    ('FL29', 'คุณโบ๊ท Freeland (TLTD เก่า)', TRUE, 'FL'),
    ('FL3', 'คุณหมิว', TRUE, 'FL'),
    ('FL30', 'คุณBob Freelance วสิษฐ์พล พุโพธิ์', TRUE, 'FL'),
    ('FL31', 'คุณชัย เคยอยู่ ISM', TRUE, 'FL'),
    ('FL32', 'pom คุณปอม จิตติมา เมฆานภายัพ', TRUE, 'FL'),
    ('FL33', 'คุณปุณ', TRUE, 'FL'),
    ('FL33-34', 'คุณธนพล มรกตวิจิตรการ', TRUE, 'FL'),
    ('FL35', 'อภิชญา ครองบุญยิ่ง(เล้ง)', TRUE, 'FL'),
    ('FL36', 'คุณดรีม', TRUE, 'FL'),
    ('FL37', 'กัญญุมา ประชาศิลป์ชัย', TRUE, 'FL'),
    ('FL38', 'คุณนิชา Bhiraj Tower', TRUE, 'FL'),
    ('FL39', 'K.Nicole (เคยอยู่Avroko)', TRUE, 'FL'),
    ('FL4', 'คุณศิริชัย เกิดลาภอนันต์', TRUE, 'FL'),
    ('FL40', 'คุณวัฒน์ คุปตะวาทิน', TRUE, 'FL'),
    ('FL41', 'คุณกุลยา สัจจวาณิชย์', TRUE, 'FL'),
    ('FL42', 'คุณภานุรุจ จรัสนิธิพร', TRUE, 'FL'),
    ('FL43', 'คุณปวริสร์', TRUE, 'FL'),
    ('FL44', 'คุณฝน', TRUE, 'FL'),
    ('FL45', 'นัท Freelance', TRUE, 'FL'),
    ('FL46', 'คุณบอย', TRUE, 'FL'),
    ('FL47', 'คุณแคท', TRUE, 'FL'),
    ('FL48', 'คุณบูม', TRUE, 'FL'),
    ('FL49', 'คุณตรีทศ พลราษฏร์ล้ำ THRITOTH POLRAJLUM', TRUE, 'FL'),
    ('FL5', 'คุณพรนภา จ่างภากร คุณปู๊', TRUE, 'FL'),
    ('FL50', 'คุณอู๊ด (DS เก่า)', TRUE, 'FL'),
    ('FL51', 'คุณมงคล', TRUE, 'FL'),
    ('FL52', 'คุณติ๊ก สุธิดา', TRUE, 'FL'),
    ('FL53', 'คุณสไปร์ท์ ออกจาก DIU', TRUE, 'FL'),
    ('FL54', 'คุณพงษ์ศิริ สุทธิชัยพฤกษ์ (คุณบอล)', TRUE, 'FL'),
    ('FL55', 'คุณนก', TRUE, 'FL'),
    ('FL56', 'คุณแจ้', TRUE, 'FL'),
    ('FL57', 'คุณสุรศักดิ์ จุมพล (ลูกค้าป้า)', TRUE, 'FL'),
    ('FL58', 'คุณอุษาวรรณ', TRUE, 'FL'),
    ('FL59', 'Toby Le Nomade เคยอยู่ Wonder by WJ)', TRUE, 'FL'),
    ('FL6', 'คุณอมฤต', TRUE, 'FL'),
    ('FL60', 'คุณแม็ก (Freelance ออกจากMom Studio)', TRUE, 'FL'),
    ('FL61', 'คุณเจ ฟรีแลนซ์ (ฺเคยทำงาน Baan Pattana กับ Brownhouse)', TRUE, 'FL'),
    ('FL62', 'คุณหมี', TRUE, 'FL'),
    ('FL63', 'คุณเมธี', TRUE, 'FL'),
    ('FL64', 'คุณ PoMm', TRUE, 'FL'),
    ('FL65', 'คุณเอ (ฟรีแลนซ์เพื่อนพี่ชาย)', TRUE, 'FL'),
    ('FL66', 'คุณเกด', TRUE, 'FL'),
    ('FL67', 'คุณตอง', TRUE, 'FL'),
    ('FL68', 'K.วิน', TRUE, 'FL'),
    ('FL69', 'คุณบิว', TRUE, 'FL'),
    ('FL7', 'คุณนัท', TRUE, 'FL'),
    ('FL70', 'คุณตั้ม', TRUE, 'FL'),
    ('FL71', 'คุณอาท Freelance (เคยทำกับคุณเต้ย Esteaque)', TRUE, 'FL'),
    ('FL72', 'คุณปุญ', TRUE, 'FL'),
    ('FL73', 'คุณเจิน', TRUE, 'FL'),
    ('FL74', 'คุณมา Freelance (เคยอยู่Chemistri) คุณกัสมา', TRUE, 'FL'),
    ('FL75', 'คุณปอ (เคยอยู่Singha Estate)', TRUE, 'FL'),
    ('FL76', 'แอน', TRUE, 'FL'),
    ('FL77', 'คุณมี่', TRUE, 'FL'),
    ('FL8', 'คุณเจ๊าะแจ๊ะ', TRUE, 'FL'),
    ('FL9', 'Khun Kittikong Pattanakitjarak คุณก้อง', TRUE, 'FL'),
    ('G001', 'GABLE', TRUE, 'G'),
    ('G002', 'กรีนแอด', TRUE, 'G'),
    ('G003', 'GIM', TRUE, 'G'),
    ('G004', 'จี.โอ อินทีเรียร์', TRUE, 'G'),
    ('G005', 'GALLERY INTERIOR', TRUE, 'G'),
    ('G006', 'Green กรีน อาร์เทค', FALSE, 'G'),
    ('G007', 'คูเฮาร์', TRUE, 'G'),
    ('G008', 'GAIA STUDIO', TRUE, 'G'),
    ('G009', 'GROUP THREE', TRUE, 'G'),
    ('G010', 'GLITT', TRUE, 'G'),
    ('G011', 'GA ARCHITECTS', TRUE, 'G'),
    ('G012', 'GOOD LUX', TRUE, 'G'),
    ('G013', 'GRU', TRUE, 'G'),
    ('G014', 'กราวด์สตูดิโอ', TRUE, 'G'),
    ('G015', 'คุณแกว(ส่วนตัว)', TRUE, 'G'),
    ('G016', 'GOOSEBERRY', TRUE, 'G'),
    ('G017', 'GREEN ARCHITECTS', TRUE, 'G'),
    ('G018', 'G49', TRUE, 'G'),
    ('G019', 'GREYMATTERS', TRUE, 'G'),
    ('G020', 'GLAMB', TRUE, 'G'),
    ('G021', 'Gris&Co', TRUE, 'G'),
    ('G022', 'Kitiya / กิติยา', TRUE, 'G'),
    ('G023', 'Green Dwel', TRUE, 'G'),
    ('G024', 'Groove Studio 2017', TRUE, 'G'),
    ('G025', 'Gratitude Design', TRUE, 'G'),
    ('G026', 'Ground Architect', TRUE, 'G'),
    ('G027', 'Golfkris Design', TRUE, 'G'),
    ('G028', 'Grieige Space Studio', TRUE, 'G'),
    ('G029', 'Green box / studio gin', TRUE, 'G'),
    ('G030', 'Greige Studio & Co Space', TRUE, 'G'),
    ('H001', 'ไฮซ์', TRUE, 'H'),
    ('H002', 'โฮม', TRUE, 'H'),
    ('H003', 'HOUSING 10 11', TRUE, 'H'),
    ('H004', 'HASSELL', TRUE, 'H'),
    ('H005', 'HBA', TRUE, 'H'),
    ('H006', 'HYBRID', TRUE, 'H'),
    ('H007', 'HARPER DESIGN', TRUE, 'H'),
    ('H008', 'HAUSBANGKOK', TRUE, 'H'),
    ('H009', 'HYPESTUGIOGESSN', TRUE, 'H'),
    ('H010', 'HAUS', TRUE, 'H'),
    ('H011', 'HI-INTERIOR DESIGN', TRUE, 'H'),
    ('H012', 'HAPPYEXHIBITTION', TRUE, 'H'),
    ('H013', 'HABITA', TRUE, 'H'),
    ('H014', 'HA DESIGN', TRUE, 'H'),
    ('H015', 'HYPOTHESIS', TRUE, 'H'),
    ('H016', 'HANSA', TRUE, 'H'),
    ('H017', 'Huippu Design', TRUE, 'H'),
    ('H018', 'Hybrid Design (คุณกรณ์) , walk in (IG)', TRUE, 'H'),
    ('H019', 'HOAA', TRUE, 'H'),
    ('H020', 'H75', TRUE, 'H'),
    ('I001', 'IA49', TRUE, 'I'),
    ('I002', 'ISM', TRUE, 'I'),
    ('I003', 'IA103', TRUE, 'I'),
    ('I004', 'IAW', TRUE, 'I'),
    ('I005', 'I DEAL 1 GROUP', TRUE, 'I'),
    ('I006', 'อินเทอร์ลุค', TRUE, 'I'),
    ('I007', 'อันทิเรียอาร์ต', TRUE, 'I'),
    ('I008', 'IDR', TRUE, 'I'),
    ('I009', 'INTERIOR VISION', TRUE, 'I'),
    ('I010', 'INNERRICH', TRUE, 'I'),
    ('I011', 'อิมเมจินัด อินทีเรีย', TRUE, 'I'),
    ('I012', 'IMOTAL', TRUE, 'I'),
    ('I013', 'INSIDEOUT', TRUE, 'I'),
    ('I014', 'IDIM', TRUE, 'I'),
    ('I015', 'INBRED', TRUE, 'I'),
    ('I016', 'IMBRED-DP', TRUE, 'I'),
    ('I017', 'IMAGINISUG', TRUE, 'I'),
    ('I018', 'IDIN ARCHITECTS', FALSE, 'I'),
    ('I019', 'I-ARCHITECTS', TRUE, 'I'),
    ('I020', 'IDEALIST', TRUE, 'I'),
    ('I021', 'INTERIA DESIGN FARM IDF', TRUE, 'I'),
    ('I022', 'ISO GROUP', TRUE, 'I'),
    ('I023', 'INDEX LIVINGMALL', TRUE, 'I'),
    ('I024', 'INNOVATIVE STUDIO', TRUE, 'I'),
    ('I025', 'IRRADIGIE MODERN', TRUE, 'I'),
    ('I026', 'INNER EXTERIORS', TRUE, 'I'),
    ('I027', 'INTERGRATED FIELD', FALSE, 'I'),
    ('I028', 'ITOK ITHAI', TRUE, 'I'),
    ('I029', 'IDIM', TRUE, 'I'),
    ('I030', 'IXORA', FALSE, 'I'),
    ('I031', 'I''N DESIGN', TRUE, 'I'),
    ('I032', 'INCRED BLE', TRUE, 'I'),
    ('I033', 'INTERIA DESIGN WORK', TRUE, 'I'),
    ('I034', 'IF (INTERGRATED FIELD)', TRUE, 'I'),
    ('I036', 'IN THE GARDEN CO.,LTD', TRUE, 'I'),
    ('I037', 'IS INNOVATIVE STUDIO', TRUE, 'I'),
    ('I038', 'IDA', TRUE, 'I'),
    ('I039', 'IDEAICAN', TRUE, 'I'),
    ('I040', 'INTERUS', TRUE, 'I'),
    ('I041', 'บจก.ไอซอร่า ดีไซน์ / IXORA', TRUE, 'I'),
    ('I042', 'INFINI AI', TRUE, 'I'),
    ('I043', 'IDIN ARCHITECTS', TRUE, 'I'),
    ('I044', 'IDAS', TRUE, 'I'),
    ('I045', 'Interus Khun Kowit Punjapaphawin 061-5416652', TRUE, 'I'),
    ('I046', 'interiorBKK', TRUE, 'I'),
    ('I047', 'ID.ID.Interior Design', TRUE, 'I'),
    ('I048', 'interiority design studo', TRUE, 'I'),
    ('I049', 'I LIKE DESIGN STUDIO', TRUE, 'I'),
    ('J002', 'JR CRGATIA', TRUE, 'J'),
    ('J003', 'JURATHIP-INTERAROI', TRUE, 'J'),
    ('J004', 'JOE&TINMAHORN', TRUE, 'J'),
    ('J005', '71 DESIGN (ใช้รหัส 1015 แทน)', TRUE, 'J'),
    ('J006', 'JATYA INTERIOR', TRUE, 'J'),
    ('J007', 'JOTIVE STUDIO', TRUE, 'J'),
    ('J008', '760 I ARCHITECT (ใช้รหัส 1016 แทน)', TRUE, 'J'),
    ('J009', 'JDS', TRUE, 'J'),
    ('J010', 'JUNSEKINO', TRUE, 'J'),
    ('J011', 'JLL', TRUE, 'J'),
    ('J012', 'JI Group', TRUE, 'J'),
    ('J013', 'junnarchitect Co.,Ltd', TRUE, 'J'),
    ('J014', 'Jarken', TRUE, 'J'),
    ('J015', 'Jitta Architect Co.,Ltd', TRUE, 'J'),
    ('J016', 'JUTI ARCHITECTS จุติ อาร์คิเท็คส์', TRUE, 'J'),
    ('J017', 'JAH Architecture and Design Co., Ltd', TRUE, 'J'),
    ('J018', 'JS Master Design', TRUE, 'J'),
    ('J019', 'JRITT', TRUE, 'J'),
    ('K001', 'น.ต.กิตติตย์', TRUE, 'K'),
    ('K004', 'KTGY', TRUE, 'K'),
    ('K005', 'กันตลักษณ์', TRUE, 'K'),
    ('K006', 'KITCHENTTE', TRUE, 'K'),
    ('K007', 'KMA', TRUE, 'K'),
    ('K008', 'กมล อาคิเทค', TRUE, 'K'),
    ('K009', 'KE LAND', TRUE, 'K'),
    ('K010', 'K PLUS K', TRUE, 'K'),
    ('K012', 'ฆภปนิก', TRUE, 'K'),
    ('K013', 'KEEP IT SIMPLE STUDIO', TRUE, 'K'),
    ('K014', 'KASEMKIJ', TRUE, 'K'),
    ('K015', 'KALD', TRUE, 'K'),
    ('K016', 'KENU', TRUE, 'K'),
    ('K017', 'KMA', TRUE, 'K'),
    ('K018', 'คณานับดีซายน์', TRUE, 'K'),
    ('K019', 'Kaph Studio', TRUE, 'K'),
    ('K020', 'Keep C design', TRUE, 'K'),
    ('K021', 'KUUWORLD', TRUE, 'K'),
    ('K022', 'klickken Studio', TRUE, 'K'),
    ('K023', 'KOHL.SPACE', TRUE, 'K'),
    ('K024', 'Kaph Studio', TRUE, 'K'),
    ('K025', 'EKAR (คุณเปี่ยม 080-5599383) มาจาก FB', TRUE, 'K'),
    ('K026', 'เคเคเอ็นพี ดีไซน์ แอนด์ คอนสตรัคชั่น', TRUE, 'K'),
    ('K027', 'kround studio', TRUE, 'K'),
    ('K028', 'KLEE', TRUE, 'K'),
    ('K029', 'kristina zonic', TRUE, 'K'),
    ('K030', 'Krittin Studio', TRUE, 'K'),
    ('K031', 'เค เค สเปซ คอนสตรัคชั่นแอนด์ อินทีเรีย', TRUE, 'K'),
    ('K032', 'Kusolsilpa Atelier', TRUE, 'K'),
    ('K033', 'Kirin Design & Living', TRUE, 'K'),
    ('K034', 'Kernel design', TRUE, 'K'),
    ('K035', 'KANANUB DESIGN CO., LTD คณานับดีซายน์', TRUE, 'K'),
    ('K036', 'KUG Studio', TRUE, 'K'),
    ('K037', 'Keen Design', TRUE, 'K'),
    ('K038', 'KAN INTERIOR DESIGN STUDIO', TRUE, 'K'),
    ('K039', 'KPM BUILT AND BUILD', TRUE, 'K'),
    ('K040', 'KARNN ARCHITECT', TRUE, 'K'),
    ('K041', 'KEF', TRUE, 'K'),
    ('K042', 'PATAMA STUDIO (Design by PATA*)', TRUE, 'K'),
    ('L001', 'LEO INTER', TRUE, 'L'),
    ('L002', 'L49', TRUE, 'L'),
    ('L003', 'LARSEN''S', TRUE, 'L'),
    ('L004', 'เลขาสถาปนิก', TRUE, 'L'),
    ('L005', 'ลิฟวิ่ง ครีเอชั่น', TRUE, 'L'),
    ('L006', 'LEO DESIGN', TRUE, 'L'),
    ('L007', 'LANDSCAPE PLANNING', TRUE, 'L'),
    ('L008', 'LANDSCAPE OF BKK', TRUE, 'L'),
    ('L009', 'L65', TRUE, 'L'),
    ('L010', 'LUX 89', TRUE, 'L'),
    ('L011', 'LAP', TRUE, 'L'),
    ('L012', 'LWS', TRUE, 'L'),
    ('L013', 'LAST WARD STUDIO', TRUE, 'L'),
    ('L014', 'LARN SIGN', TRUE, 'L'),
    ('L015', 'LCO Landscape Collaboration', TRUE, 'L'),
    ('L016', 'LUKID', TRUE, 'L'),
    ('L017', 'Lucid Dream Design Co.,Ltd', TRUE, 'L'),
    ('L018', 'Lalida / ลลิดา', TRUE, 'L'),
    ('L019', 'Lumikraft', TRUE, 'L'),
    ('L020', 'larn sign', TRUE, 'L'),
    ('L021', 'Laguna', TRUE, 'L'),
    ('L022', 'ลลดา', TRUE, 'L'),
    ('L023', 'Lupine (ลูพีน)', TRUE, 'L'),
    ('L024', 'LEA PHUKET', TRUE, 'L'),
    ('L025', 'Loam Artisanal Living (Fur styling) โทรเข้าโชว์รูม', TRUE, 'L'),
    ('L026', 'LANDOMS STUDIO', TRUE, 'L'),
    ('L027', 'lalada villa', TRUE, 'L'),
    ('L028', 'Larn Sign Abstact', TRUE, 'L'),
    ('L029', 'Luxelife.Studio', TRUE, 'L'),
    ('L030', 'LNN Interior Design Studio', TRUE, 'L'),
    ('L031', 'LN Design69', TRUE, 'L'),
    ('L032', 'Lisense', TRUE, 'L'),
    ('L033', 'Laan architech', TRUE, 'L'),
    ('L034', 'Lenth Studio', TRUE, 'L'),
    ('L035', 'Longgoy Architect', TRUE, 'L'),
    ('L036', 'love architects co., ltd.', TRUE, 'L'),
    ('L037', 'Looklen Architects', TRUE, 'L'),
    ('M001', 'METRIC CONCEPTS', TRUE, 'M'),
    ('M002', 'เมฆอินทีเรีย', TRUE, 'M'),
    ('M003', 'MKS', TRUE, 'M'),
    ('M004', 'MLTD', TRUE, 'M'),
    ('M005', 'MAGENTA', TRUE, 'M'),
    ('M006', 'มัณชิมา', TRUE, 'M'),
    ('M007', 'MLTI STUDIO 2000', TRUE, 'M'),
    ('M009', 'METRO LANDSCAPE', TRUE, 'M'),
    ('M010', 'MAGNUS PROJECT', TRUE, 'M'),
    ('M011', 'MASSIVE DESIGN', TRUE, 'M'),
    ('M012', 'MODEL 1 TO 1', TRUE, 'M'),
    ('M014', 'MEAN MCREMINA', TRUE, 'M'),
    ('M015', 'MINIMAL RICH', TRUE, 'M'),
    ('M016', 'M&A', TRUE, 'M'),
    ('M017', 'MIND SCAPE', TRUE, 'M'),
    ('M018', 'ME2 Studio', TRUE, 'M'),
    ('M019', 'MIND', FALSE, 'M'),
    ('M020', 'MIN DESIGN', TRUE, 'M'),
    ('M021', 'MAKEASCENE', TRUE, 'M'),
    ('M022', 'MODULA DESIGN', TRUE, 'M'),
    ('M023', 'เมพท์อาร์คิเทค', TRUE, 'M'),
    ('M024', 'MADA DESIGN', TRUE, 'M'),
    ('M025', 'MIH', TRUE, 'M'),
    ('M026', 'M2PLUS', TRUE, 'M'),
    ('M027', 'M SPACE', TRUE, 'M'),
    ('M028', 'MAGLA', TRUE, 'M'),
    ('M029', 'MAYRAY STUDIO', TRUE, 'M'),
    ('M030', 'MPD STUDIO', TRUE, 'M'),
    ('M031', 'Maincourse Architect', TRUE, 'M'),
    ('M032', 'Moments Studio', TRUE, 'M'),
    ('M033', 'Mom Studio', TRUE, 'M'),
    ('M034', 'Mylivingroom Online - OA', TRUE, 'M'),
    ('M035', 'Mol Studio', TRUE, 'M'),
    ('M036', 'mavelsia มาเวลเซีย', TRUE, 'M'),
    ('M037', 'Commonspace Architect', TRUE, 'M'),
    ('M038', 'Mind Architect (LINE OA)', TRUE, 'M'),
    ('M039', 'MHK Studio', TRUE, 'M'),
    ('M040', 'Manmade interior', TRUE, 'M'),
    ('M041', 'Maps Design', TRUE, 'M'),
    ('M042', 'Millimade Design Studio', TRUE, 'M'),
    ('M043', 'MD Studio', TRUE, 'M'),
    ('M044', 'Mun Architects', TRUE, 'M'),
    ('M045', 'Mirai Design Studio', TRUE, 'M'),
    ('M046', 'MULLER DESIGN SOLUTION', TRUE, 'M'),
    ('M047', 'Masterrmind', TRUE, 'M'),
    ('M048', 'MARS Studio Design รั', TRUE, 'M'),
    ('M049', 'MOA Modern of livable Art', TRUE, 'M'),
    ('M050', 'MTM Design', TRUE, 'M'),
    ('M051', 'MOTT Interior Design Firm', TRUE, 'M'),
    ('M052', 'MYTIRA Design', TRUE, 'M'),
    ('M053', 'MOA Studio', TRUE, 'M'),
    ('M054', 'MOAR', TRUE, 'M'),
    ('M055', 'MW STUDIO', TRUE, 'M'),
    ('M056', 'Metaphor Design', TRUE, 'M'),
    ('M057', 'Minor', TRUE, 'M'),
    ('M058', 'Madeinterior', TRUE, 'M'),
    ('N001', 'ไม่มีผู้ออกแบบ', TRUE, 'N'),
    ('N002', 'ทำแบบร่วมกัน', TRUE, 'N'),
    ('N003', 'NAGA CONCEPTS', TRUE, 'N'),
    ('N004', 'นายช่างไทย', TRUE, 'N'),
    ('N005', 'มนัสเอ็มเตอร์ไพรซ์', TRUE, 'N'),
    ('N006', 'นายช่างสยาม', TRUE, 'N'),
    ('N007', 'เนาวรัตน์พัฒนาการ', TRUE, 'N'),
    ('N009', 'NGRIT KITCHEN', TRUE, 'N'),
    ('N010', 'โนเบิล', TRUE, 'N'),
    ('N011', 'NAVA DESIGN', TRUE, 'N'),
    ('N012', '195 ARCHITECH (ใช้ 1001 แทน)', TRUE, 'N'),
    ('N013', 'NC GROUP', TRUE, 'N'),
    ('N014', 'นูก้า', TRUE, 'N'),
    ('N015', '1819 LANDSCAPE (ใช้ 1002 แทน)', TRUE, 'N'),
    ('N016', '99 DD (ใช้ 1003 แทน)', TRUE, 'N'),
    ('N017', 'NINANA', TRUE, 'N'),
    ('N018', 'NILLq', TRUE, 'N'),
    ('N019', 'NINE DESIGN', TRUE, 'N'),
    ('N020', 'NEO SPACE', TRUE, 'N'),
    ('N021', 'NWD Architect', TRUE, 'N'),
    ('N022', 'Netrade asia', TRUE, 'N'),
    ('N023', 'NWN', TRUE, 'N'),
    ('N024', 'Nachapon Rujirasopon Studio', TRUE, 'N'),
    ('N025', 'NAD Design Studio', TRUE, 'N'),
    ('N026', 'NCN Interior Design', TRUE, 'N'),
    ('N027', 'Nerd studio', TRUE, 'N'),
    ('N028', 'N7A', TRUE, 'N'),
    ('N029', 'NN ARCHITECTS', TRUE, 'N'),
    ('N030', 'Studio NSD', TRUE, 'N'),
    ('N031', 'Nitaprow', TRUE, 'N'),
    ('N032', 'Natthada Design', TRUE, 'N'),
    ('O001', 'ORBIT', TRUE, 'O'),
    ('O002', 'ONIS', TRUE, 'O'),
    ('O003', 'องศา อาคิเทค', TRUE, 'O'),
    ('O004', 'OFSCALE', TRUE, 'O'),
    ('O005', 'ออโต้คอน', TRUE, 'O'),
    ('O006', 'ออกัส', TRUE, 'O'),
    ('O007', 'OF&J', TRUE, 'O'),
    ('O008', 'ONINO CO.,LTD', TRUE, 'O'),
    ('O009', 'ONFLOOR DESIGN', TRUE, 'O'),
    ('O010', 'ORIGINAL STUDIO', TRUE, 'O'),
    ('O011', 'ORIGIN', TRUE, 'O'),
    ('O012', 'OUB INTERIOR', TRUE, 'O'),
    ('O013', 'ORIZZONTE', TRUE, 'O'),
    ('O014', 'ORIGINAL', TRUE, 'O'),
    ('O015', 'OHELLO', TRUE, 'O'),
    ('O016', 'ALL ZONE', TRUE, 'O'),
    ('O017', 'โอเนีย', TRUE, 'O'),
    ('O018', 'Officer A1', TRUE, 'O'),
    ('O019', 'Open Air', TRUE, 'O'),
    ('O020', 'OBA', TRUE, 'O'),
    ('O021', 'Ong & Ong', TRUE, 'O'),
    ('O023', 'OCD', TRUE, 'O'),
    ('O024', 'ALL ZONE', TRUE, 'O'),
    ('O025', 'ONIS', TRUE, 'O'),
    ('O026', 'ONG ONG', TRUE, 'O'),
    ('O027', 'OBD', TRUE, 'O'),
    ('O028', 'OPEN BOX', TRUE, 'O'),
    ('O029', 'โอกาส', TRUE, 'O'),
    ('O030', 'OPEN SPACE', TRUE, 'O'),
    ('O031', 'Oub Design (คุณนพดล เอี่ยมบำรุง)', FALSE, 'O'),
    ('O032', 'OPO', TRUE, 'O'),
    ('O033', 'Oneone Design', TRUE, 'O'),
    ('O034', 'Ong & Ong', TRUE, 'O'),
    ('O035', 'OVER EXPECT STUDIO COMPANY LIMITED', TRUE, 'O'),
    ('O036', 'Owner เจ้าของโครงการ', TRUE, 'O'),
    ('O037', 'OLTE', TRUE, 'O'),
    ('O038', 'Otello Studio', TRUE, 'O'),
    ('O039', 'OPH Architects คุณเค', TRUE, 'O'),
    ('O040', 'One and a half', TRUE, 'O'),
    ('O041', 'Out & About architect', TRUE, 'O'),
    ('O042', 'original mind Studio / OG.M', TRUE, 'O'),
    ('O043', 'OUAD Design & Gallery', TRUE, 'O'),
    ('ON001', 'The Mall', TRUE, 'Owner'),
    ('P001', 'Powarint', TRUE, 'P'),
    ('P002', 'PIA', TRUE, 'P'),
    ('P003', 'พรัสมา', TRUE, 'P'),
    ('P004', 'โพรีแกรม', TRUE, 'P'),
    ('P005', 'PREVIEW INTERIOR', TRUE, 'P'),
    ('P006', 'พาสเมอร์&เทอร์เมอร์', TRUE, 'P'),
    ('P007', 'P49', TRUE, 'P'),
    ('P009', 'PL DESIGN', TRUE, 'P'),
    ('P012', 'POSED INTERIOR', TRUE, 'P'),
    ('P013', 'PLUS', TRUE, 'P'),
    ('P015', 'P_LANDSCAPE', TRUE, 'P'),
    ('P017', 'PEPER WIZARD', TRUE, 'P'),
    ('P018', 'PACE DEVELOPMENT', TRUE, 'P'),
    ('P019', 'PROGRESSIVE', TRUE, 'P'),
    ('P021', 'PARK STONE', TRUE, 'P'),
    ('P022', 'P SPACE', TRUE, 'P'),
    ('P023', 'PROCESS INTERIOR', TRUE, 'P'),
    ('P025', 'PLAN-A-DESIGN', TRUE, 'P'),
    ('P026', 'PAA Studio', TRUE, 'P'),
    ('P027', 'PROMPT', TRUE, 'P'),
    ('P028', 'PICO', TRUE, 'P'),
    ('P029', 'PWP', TRUE, 'P'),
    ('P030', 'PROCESS LANDSCAPE', TRUE, 'P'),
    ('P031', 'P VIRIYA', TRUE, 'P'),
    ('P032', 'P DESIGN', TRUE, 'P'),
    ('P033', 'PALMER&TURNER', TRUE, 'P'),
    ('P034', 'PPA', TRUE, 'P'),
    ('P035', 'PA-INTERIA', TRUE, 'P'),
    ('P036', 'PM DESIGN', TRUE, 'P'),
    ('P037', 'PYE', TRUE, 'P'),
    ('P038', 'PRODUCTION OF SPACE', TRUE, 'P'),
    ('P040', 'PARTY SPACE', TRUE, 'P'),
    ('P041', 'PHYSICALIST', TRUE, 'P'),
    ('P042', 'PL DESIGN', TRUE, 'P'),
    ('P043', 'PHTAA LIVING DESIGN', TRUE, 'P'),
    ('P044', 'PA', TRUE, 'P'),
    ('P045', 'P INTERIOR', TRUE, 'P'),
    ('P047', 'PLUS', TRUE, 'P'),
    ('P048', 'พอดี / Padee', TRUE, 'P'),
    ('P049', 'PLAMMER & TORNER', TRUE, 'P'),
    ('P050', 'PADEE', TRUE, 'P'),
    ('P051', 'Proportion Design Studio', TRUE, 'P'),
    ('P052', 'PAL Studio', TRUE, 'P'),
    ('P053', 'Plan&Objects', TRUE, 'P'),
    ('P054', 'Paradigm Shift design', TRUE, 'P'),
    ('P055', 'Paper Design', TRUE, 'P'),
    ('P056', 'PLP', TRUE, 'P'),
    ('P057', 'purpose of space', TRUE, 'P'),
    ('P058', 'Physicalist', TRUE, 'P'),
    ('P059', 'Panorama', TRUE, 'P'),
    ('P060', 'Pearl Village', TRUE, 'P'),
    ('P061', 'P Landscape PLA', TRUE, 'P'),
    ('P062', 'Pava architect', TRUE, 'P'),
    ('P063', 'Pannaria Design (ลูกค้า FB)', TRUE, 'P'),
    ('P064', 'พศ อาร์คิเทค', TRUE, 'P'),
    ('P065', 'Pure Architect', TRUE, 'P'),
    ('P066', 'Pisit Architect Atelier Co., Ltd.', TRUE, 'P'),
    ('P067', 'Plan Studio Co., Ltd.', TRUE, 'P'),
    ('P068', 'Pun Su Pol Architect', TRUE, 'P'),
    ('P069', 'PACMAN STUDIO COMPANY LIMITED คุณฐาปนา บริษัท แพคแมน สตูดิโอ จำกัด', TRUE, 'P'),
    ('P070', 'PONNA STUDIO', TRUE, 'P'),
    ('P071', 'Planmakr', TRUE, 'P'),
    ('P072', 'Patta Studio', TRUE, 'P'),
    ('P073', 'Pattakit Design & Construction', TRUE, 'P'),
    ('P074', 'PROJECT PLANING SERVICE CO., LTD', TRUE, 'P'),
    ('P075', 'Predec', TRUE, 'P'),
    ('P076', 'PITIBOON (piti boon design)', TRUE, 'P'),
    ('P077', 'PRUSSIAN BLUE DESIGN', TRUE, 'P'),
    ('P078', 'PITITHITI / ปิติฐิติ', TRUE, 'P'),
    ('P079', 'Positive Monday (Walk in Showroom)', TRUE, 'P'),
    ('P080', 'Puen-din Architects: ผืนดินสถาปนิก', TRUE, 'P'),
    ('P081', 'PROUDIAN', TRUE, 'P'),
    ('P082', 'Paon Architects', TRUE, 'P'),
    ('P083', 'PARANA SPACE', TRUE, 'P'),
    ('P084', 'PALS Co., Ltd.', TRUE, 'P'),
    ('P085', 'planet studio', TRUE, 'P'),
    ('P086', 'pi+I pitiarchitect', TRUE, 'P'),
    ('P087', 'Park&Associate', TRUE, 'P'),
    ('P088', 'pi+I STUDIO MONOLITH', TRUE, 'P'),
    ('P089', 'please feel free', TRUE, 'P'),
    ('P090', 'plug Studio', TRUE, 'P'),
    ('P091', 'PIYA INTER ปิยะ อินเตอร์', TRUE, 'P'),
    ('P092', 'PIORNI', TRUE, 'P'),
    ('P093', 'Pleng.design', TRUE, 'P'),
    ('Q001', 'QUATRE INTERIOR', TRUE, 'Q'),
    ('Q002', 'QUATREAR CHITECT', TRUE, 'Q'),
    ('Q003', 'QUASAR PLUS', TRUE, 'Q'),
    ('Q004', 'QA Design', TRUE, 'Q'),
    ('R001', 'สนง.ออกแบบระฟ้า', TRUE, 'R'),
    ('R002', 'ROOF', TRUE, 'R'),
    ('R003', 'RDG', TRUE, 'R'),
    ('R004', 'RED LANDSCAPE', TRUE, 'R'),
    ('R005', 'RA+', TRUE, 'R'),
    ('R006', 'RJ&D', TRUE, 'R'),
    ('R007', 'Redhouse Design Co.,Ltd', TRUE, 'R'),
    ('R008', 'ROX SPACE', TRUE, 'R'),
    ('R009', 'RDM Desing Group', TRUE, 'R'),
    ('R010', 'Ralh Architecture and Design', TRUE, 'R'),
    ('R021', 'REDLAND', TRUE, 'R'),
    ('R022', 'RAD', TRUE, 'R'),
    ('R023', 'Rada interior design studio', TRUE, 'R'),
    ('R024', 'RYCE Architects', TRUE, 'R'),
    ('R025', 'Rule Of Thirds Interior Design Studio', TRUE, 'R'),
    ('R026', 'ROOF TOP INTERIOR DESIGN&CONSTRUCTION COMPANY LIMITED', TRUE, 'R'),
    ('R027', 'Rums Design', TRUE, 'R'),
    ('R028', 'Red House', TRUE, 'R'),
    ('R029', 'ralph arhchitecture', TRUE, 'R'),
    ('R030', 'Rad Studio', TRUE, 'R'),
    ('S005', 'STUDIO 54', TRUE, 'S'),
    ('S006', '21 DESIGN (ใช้รหัส 1004 แทน)', TRUE, 'S'),
    ('S007', 'SPACE', TRUE, 'S'),
    ('S008', 'SUNLAY', TRUE, 'S'),
    ('S009', '23 ID (ใช้รหัส 1012 แทน)', TRUE, 'S'),
    ('S010', 'Studio Aeroplane', TRUE, 'S'),
    ('S013', '3045 STUDIO (ใช้รหัส 1005 แทน)', TRUE, 'S'),
    ('S014', 'SPACE TIME', TRUE, 'S'),
    ('S018', 'SITY SPACE', TRUE, 'S'),
    ('S019', 'STARDUST DESIGN', TRUE, 'S'),
    ('S021', 'STEM DESIGN', TRUE, 'S'),
    ('S023', 'SANSIRI', TRUE, 'S'),
    ('S024', 'STEVEN J.LEACH', TRUE, 'S'),
    ('S025', 'SPACE ARCHITECTS', TRUE, 'S'),
    ('S026', 'SSW', TRUE, 'S'),
    ('S028', 'STUDIO FORWORD', TRUE, 'S'),
    ('S029', 'SPACE INTERIOR', TRUE, 'S'),
    ('S030', 'SIT INTERIOR', TRUE, 'S'),
    ('S031', 'STUDIO VERY', TRUE, 'S'),
    ('S033', 'STUDIO 906', TRUE, 'S'),
    ('S034', 'SIAMPIWAN', TRUE, 'S'),
    ('S035', 'SPACE METRIX', TRUE, 'S'),
    ('S037', 'SAVAS', TRUE, 'S'),
    ('S038', 'SPACE TO DESIGN', TRUE, 'S'),
    ('S041', 'SIGN IN', TRUE, 'S'),
    ('S043', 'S2 ARCHITECTS', TRUE, 'S'),
    ('S044', 'STUDIO SPAVTNIK', TRUE, 'S'),
    ('S045', 'SQ ARCHITECTS', TRUE, 'S'),
    ('S046', 'SO', TRUE, 'S'),
    ('S047', 'สตูอิโอ แอทซิเทค', TRUE, 'S'),
    ('S048', 'STUDIO ARCHITECTS Stu/ D/O', TRUE, 'S'),
    ('S049', 'IS AM ARE', TRUE, 'S'),
    ('S050', 'STUDIO AGUI', TRUE, 'S'),
    ('S051', 'SYMBIOSIS', TRUE, 'S'),
    ('S052', 'Somdoon Architects', TRUE, 'S'),
    ('S053', 'SCPHISTICA NOVA', TRUE, 'S'),
    ('S054', 'SANITUS', TRUE, 'S'),
    ('S055', 'SANTHAYA', TRUE, 'S'),
    ('S056', 'SCALE ARCHITECTS', TRUE, 'S'),
    ('S057', 'STUDIO NO MAD', TRUE, 'S'),
    ('S058', 'SPACE ARCHITECTS', TRUE, 'S'),
    ('S059', 'SOUL SONCEPT', TRUE, 'S'),
    ('S060', 'SANDCAA', TRUE, 'S'),
    ('S061', 'SODA', TRUE, 'S'),
    ('S062', 'STUDIO ARNATTA', TRUE, 'S'),
    ('S063', 'STUDIO NOMATTER', TRUE, 'S'),
    ('S064', '11 เมษา', TRUE, 'S'),
    ('S065', 'SIA', TRUE, 'S'),
    ('S066', 'STUDIO YAK', TRUE, 'S'),
    ('S067', 'SALLA DESIGN', TRUE, 'S'),
    ('S068', 'STUDIO 3C', TRUE, 'S'),
    ('S069', 'SPACE MATTER', TRUE, 'S'),
    ('S070', 'Sahacha', TRUE, 'S'),
    ('S071', 'SV ARCHITECTS', TRUE, 'S'),
    ('S072', 'Six Senses', TRUE, 'S'),
    ('S073', 'Studio Freehand', TRUE, 'S'),
    ('S074', 'Studio Palanet', TRUE, 'S'),
    ('S075', 'ซัน ดีไซน์', TRUE, 'S'),
    ('S076', 'SCALEUP ARCHITECT', TRUE, 'S'),
    ('S077', 'สตีลไลน์', TRUE, 'S'),
    ('S078', 'Studio Plannt', TRUE, 'S'),
    ('S079', 'Set.A.Plan', TRUE, 'S'),
    ('S080', 'สถาปนิกเมนคอร์ส คุณคิม', TRUE, 'S'),
    ('S081', 'Sevenhouse', TRUE, 'S'),
    ('S082', 'Studio Pal&Co', TRUE, 'S'),
    ('S083', 'SOHO Hospitaligy', TRUE, 'S'),
    ('S084', 'S zong Architect & Associate (SA)', TRUE, 'S'),
    ('S085', 'Salt Design Studio Bkk', TRUE, 'S'),
    ('S086', 'Siam Piwat', TRUE, 'S'),
    ('S087', 'Stay Interior Design', TRUE, 'S'),
    ('S088', 'Simply Space Studio (เคยอยู่ P49) คุณเจต /', TRUE, 'S'),
    ('S089', 'Studio Pin', TRUE, 'S'),
    ('S090', 'Studio.peace', TRUE, 'S'),
    ('S091', 'Spacecraft', TRUE, 'S'),
    ('S092', 'SSAA', TRUE, 'S'),
    ('S093', 'Studio S.P.Y', TRUE, 'S'),
    ('S094', 'Studio Work In Progress', TRUE, 'S'),
    ('S095', 'Studio Perception', TRUE, 'S'),
    ('S096', 'Studio Groovy', TRUE, 'S'),
    ('S097', 'Studio Drift', TRUE, 'S'),
    ('S098', 'Studio MW', TRUE, 'S'),
    ('S099', 'Seven Sep', TRUE, 'S'),
    ('S100', 'Studio PLP', TRUE, 'S'),
    ('S101', 'studio freehand ใช้ S073', TRUE, 'S'),
    ('S102', 'Studio Prang', TRUE, 'S'),
    ('S103', 'Studiovilaa', TRUE, 'S'),
    ('S104', 'Sompratthanadesign', TRUE, 'S'),
    ('S105', 'SO ARCHITECTS', TRUE, 'S'),
    ('S106', 'Siwa Interior', TRUE, 'S'),
    ('S107', 'Studio Poto', TRUE, 'S'),
    ('S108', 'Sojourn design studio', TRUE, 'S'),
    ('S109', 'StudioPATH', TRUE, 'S'),
    ('S110', 'SPECTER ARCHITECT', TRUE, 'S'),
    ('S111', 'Studio NSD', TRUE, 'S'),
    ('S112', 'Sari Smit', TRUE, 'S'),
    ('S113', 'Studiohand', TRUE, 'S'),
    ('S114', 'The Simple Plan / . Keen Condo', TRUE, 'S'),
    ('S115', 'STUDIO KRUBKA', TRUE, 'S'),
    ('S116', 'Sevensep', TRUE, 'S'),
    ('S117', 'SP Line Studio', TRUE, 'S'),
    ('S118', 'Set A Plan', TRUE, 'S'),
    ('S119', 'Salmon Architect', TRUE, 'S'),
    ('S120', 'Salad Box', TRUE, 'S'),
    ('S121', 'Say Studio', TRUE, 'S'),
    ('S122', 'Stu/D/O Architects', TRUE, 'S'),
    ('S123', 'Studio.dimention', TRUE, 'S'),
    ('S124', 'Sail & Sahaai', TRUE, 'S'),
    ('S125', 'Scene Studio', TRUE, 'S'),
    ('S126', 'Somoon', TRUE, 'S'),
    ('S127', 'Spaceology', TRUE, 'S'),
    ('S128', 'SHMA', TRUE, 'S'),
    ('S129', 'Studio 1:10', TRUE, 'S'),
    ('S130', 'SCENSE STUDIO', TRUE, 'S'),
    ('S131', 'Sense Sign', TRUE, 'S'),
    ('S132', 'SPRING PALETTE DESIGN', TRUE, 'S'),
    ('S133', 'SJ Sukjai', TRUE, 'S'),
    ('S134', 'Sata Na Architects', TRUE, 'S'),
    ('T001', 'Thaiwah', TRUE, 'T'),
    ('T004', 'TIGON DESIGN', TRUE, 'T'),
    ('T005', '250 (ใช้รหัส 1014 แทน)', TRUE, 'T'),
    ('T007', 'THE THIRD', TRUE, 'T'),
    ('T008', 'TECHNICA NOVA', TRUE, 'T'),
    ('T009', '2D PLUS (ใช้รหัส 1006 แทน)', TRUE, 'T'),
    ('T010', 'TASK INTERIOR', TRUE, 'T'),
    ('T011', 'TMC', TRUE, 'T'),
    ('T012', 'T''int', TRUE, 'T'),
    ('T015', 'TID', TRUE, 'T'),
    ('T017', 'TCC', TRUE, 'T'),
    ('T018', 'TIERRB DESIGN', TRUE, 'T'),
    ('T019', 'TASCANA VILLEY', TRUE, 'T'),
    ('T020', 'TAAK Intrior', TRUE, 'T'),
    ('T021', 'THE TREE CENTURY', TRUE, 'T'),
    ('T022', '3 PLUS 1 (ใช้รหัส 1007 แทน)', TRUE, 'T'),
    ('T023', 'THEME ARCHITECTS', TRUE, 'T'),
    ('T024', '3C INTERIOR (ใช้รหัส 1008 แทน)', TRUE, 'T'),
    ('T025', '27 ARCHTECT (ใช้รหัส 1009 แทน)', TRUE, 'T'),
    ('T026', 'TECTONIC DESIGN', TRUE, 'T'),
    ('T027', '3D INTERIOR (ใช้รหัส 1010 แทน)', TRUE, 'T'),
    ('T029', 'TAN DEM', TRUE, 'T'),
    ('T030', 'TEAC', TRUE, 'T'),
    ('T031', 'TMOTIV', TRUE, 'T'),
    ('T032', 'TIME CUT CAMP', TRUE, 'T'),
    ('T033', 'TLTD', TRUE, 'T'),
    ('T034', 'TRIMADE STUDIO', TRUE, 'T'),
    ('T035', 'TEN BY TEN', TRUE, 'T'),
    ('T036', 'TRIPROPERTY', TRUE, 'T'),
    ('T037', '3BS (ใช้รหัส 1011 แทน)', TRUE, 'T'),
    ('T038', 'TBT&DAF', TRUE, 'T'),
    ('T039', 'KHUN TATA', TRUE, 'T'),
    ('T040', 'TEN BY TEN DAF', TRUE, 'T'),
    ('T041', 'TANN', TRUE, 'T'),
    ('T042', 'TUATAR INTER DESIGN', TRUE, 'T'),
    ('T043', 'TM DESIGN', TRUE, 'T'),
    ('T044', 'TK STUDIO', TRUE, 'T'),
    ('T045', 'THAT '' ITS INTERIOR', TRUE, 'T'),
    ('T046', 'TECTONIX LANDSCAPE', TRUE, 'T'),
    ('T047', 'Toscana Valley Interior', TRUE, 'T'),
    ('T048', 'Three Flag', TRUE, 'T'),
    ('T049', 'TRM Studio', TRUE, 'T'),
    ('T050', 'Tuesday Design', TRUE, 'T'),
    ('T051', 'THEORY & CO. INTERIOR DESIGN', TRUE, 'T'),
    ('T052', 'tanyatania Interior Design Studio', TRUE, 'T'),
    ('T068', 'TOFF (THAILAND)', TRUE, 'T'),
    ('T069', 'Atelier dreamc', TRUE, 'T'),
    ('T070', 'tanyatania Interior Design Studio', TRUE, 'T'),
    ('T081', 'Tanda Design studio', TRUE, 'T'),
    ('T082', 'THAAN STUDIO', TRUE, 'T'),
    ('T083', 'Tierra design(Thailand) Ltd.', TRUE, 'T'),
    ('T084', 'The Mall', TRUE, 'T'),
    ('T085', 'The Collective Studio', TRUE, 'T'),
    ('T086', 'Tara Studio', TRUE, 'T'),
    ('T087', 'TOEY Interior', TRUE, 'T'),
    ('T088', 'THE SIMPLE PLAN', TRUE, 'T'),
    ('T089', 'TXTURE LAB oratory', TRUE, 'T'),
    ('T090', 'Topic Design', TRUE, 'T'),
    ('T091', 'Taan Studio', TRUE, 'T'),
    ('T092', 'The Emperor House Co.,Ltd', TRUE, 'T'),
    ('T093', 'TADAH', TRUE, 'T'),
    ('T094', 'Toby Le Nomade', TRUE, 'T'),
    ('T095', 'TIDTANG STUDIO COMPANY LIMITED', TRUE, 'T'),
    ('T096', 'TASTETELL CO.LTD', TRUE, 'T'),
    ('U001', 'URBAN AND ASSOCIATE', TRUE, 'U'),
    ('U002', 'ยูคาห์', TRUE, 'U'),
    ('U003', 'U.X.D', TRUE, 'U'),
    ('U004', 'ยูโรป้า โคเปอร์เรชั่น', TRUE, 'U'),
    ('U006', 'URBANIQUE', TRUE, 'U'),
    ('U007', 'Urban Home', TRUE, 'U'),
    ('U008', 'urban architect', TRUE, 'U'),
    ('U009', 'uad design place', TRUE, 'U'),
    ('U010', 'Urban Capital and Development', TRUE, 'U'),
    ('U011', 'Undergroundstudio', TRUE, 'U'),
    ('U012', 'Ultitled Department Studio', TRUE, 'U'),
    ('U013', 'Uni-Design', TRUE, 'U'),
    ('V002', 'วิศย์สยาม', TRUE, 'V'),
    ('V003', 'วรัญ ดีไซต์', TRUE, 'V'),
    ('V004', 'VASLAB', TRUE, 'V'),
    ('V005', 'VAURA', TRUE, 'V'),
    ('V006', 'VZUN ARCHITECTS', TRUE, 'V'),
    ('V007', 'V2inarchitects', TRUE, 'V'),
    ('V008', 'Workwell-studio', TRUE, 'V'),
    ('V009', 'V House Studio', TRUE, 'V'),
    ('V010', 'Visiona', TRUE, 'V'),
    ('V011', 'Vida', TRUE, 'V'),
    ('V012', 'VESSU collaboration', TRUE, 'V'),
    ('V013', 'V2 Design Studio', TRUE, 'V'),
    ('V014', 'VELLA ARCHITET', TRUE, 'V'),
    ('V015', 'VOLUME DESIGH', TRUE, 'V'),
    ('V016', 'VILAA+ Studio Vilaa co., ltd', TRUE, 'V'),
    ('V017', 'Virada studi', TRUE, 'V'),
    ('V018', 'Vinotto', TRUE, 'V'),
    ('V019', 'Varp Studio', TRUE, 'V'),
    ('V020', 'Vide Design Studio', TRUE, 'V'),
    ('V021', 'Vsa', TRUE, 'V'),
    ('V022', 'Vair Design', TRUE, 'V'),
    ('V023', 'V BUILT DECORATE CO., LTD.', TRUE, 'V'),
    ('W001', 'WOOD BAGOT', TRUE, 'W'),
    ('W003', 'WD DESIGN', TRUE, 'W'),
    ('W004', 'WOLVES DESIGN', TRUE, 'W'),
    ('W005', 'WOHA DESIGN', TRUE, 'W'),
    ('W006', 'WT DESIGN', TRUE, 'W'),
    ('W007', 'WOOL SPACE', TRUE, 'W'),
    ('W008', 'WVK', TRUE, 'W'),
    ('W009', 'WHITE SPACE', TRUE, 'W'),
    ('W010', 'WM INAGINEER', TRUE, 'W'),
    ('W011', 'WRS', TRUE, 'W'),
    ('W012', 'WARANZ', TRUE, 'W'),
    ('W014', 'WHITELINESTUDIO', TRUE, 'W'),
    ('W015', 'WISE LINE DESIGN CO.,LTD', TRUE, 'W'),
    ('W016', 'WILSAN FRANCE', TRUE, 'W'),
    ('W017', 'WUF HOUSE DESIGN CO.,LTD.', TRUE, 'W'),
    ('W018', 'Wasu Architects', TRUE, 'W'),
    ('W019', 'Workspace Architecture Studio', TRUE, 'W'),
    ('W020', 'Wad Architure', TRUE, 'W'),
    ('W021', 'WVS', TRUE, 'W'),
    ('W022', 'WARA architect', TRUE, 'W'),
    ('W026', 'Wide House Studio', TRUE, 'W'),
    ('W027', 'WHITE LINE LABORATORY', TRUE, 'W'),
    ('W028', 'WS (Minta)', TRUE, 'W'),
    ('W029', 'Waa Studio', TRUE, 'W'),
    ('W030', 'Wellhomes', TRUE, 'W'),
    ('X001', 'X-site design studio', TRUE, 'X'),
    ('Y001', 'YES IT GREST', TRUE, 'Y'),
    ('Y002', 'YOO', TRUE, 'Y'),
    ('Y003', 'Y.C. CONCEPT', TRUE, 'Y'),
    ('Y010', 'Yaaf', TRUE, 'Y'),
    ('Z001', 'ZAING', TRUE, 'Z'),
    ('Z002', 'ZIA DESIGN', TRUE, 'Z'),
    ('Z003', 'ZERO DEEGREE', TRUE, 'Z'),
    ('w024', 'WILLA Interior', TRUE, 'W'),
    ('w025', 'White House', TRUE, 'W'),
    ('ก001', 'กล่องดินสอ', TRUE, 'ภาษาไทย'),
    ('ก002', 'พศ อาร์คิเทค', TRUE, 'ภาษาไทย'),
    ('ก003', 'ถนน Studio', TRUE, 'ภาษาไทย'),
    ('ก004', 'เบญจมาศ', TRUE, 'ภาษาไทย'),
    ('ก005', 'เวลดีไซน์เกม', TRUE, 'ภาษาไทย'),
    ('ก006', 'คมคาย ดีไซน์', TRUE, 'ภาษาไทย'),
    ('ก007', 'พาออน paon architect', TRUE, 'ภาษาไทย'),
    ('ก008', 'ลีรักษ์โฮม', TRUE, 'ภาษาไทย'),
    ('ก009', 'ศูนย์มิลลิม', TRUE, 'ภาษาไทย'),
    ('ก010', 'ฝนม่วง', TRUE, 'ภาษาไทย'),
    ('ก011', 'พอ สถาปัตย์', TRUE, 'ภาษาไทย'),
    ('ก012', 'ออกแบบ 2014', TRUE, 'ภาษาไทย'),
    ('ก013', 'กาล อาค์คิเทค', TRUE, 'ภาษาไทย'),
    ('ก014', 'ส ถา ณ สถาปนิก', TRUE, 'ภาษาไทย'),
    ('ก015', 'ลูกเล่น สถาปนิก', TRUE, 'ภาษาไทย'),
    ('ก016', 'ซีโร่เซนติเมตร', TRUE, 'ภาษาไทย'),
    ('ก017', 'ทิศทางสตูดิโอ', TRUE, 'ภาษาไทย')
       ) AS v(code, name, active, source_sheet)
 WHERE NOT EXISTS (
        SELECT 1 FROM sales.designer d WHERE d.code = v.code);
