// Named imports are lucide-react's stable public API. Earlier this file used deep
// `lucide-react/dist/esm/icons/*.js` paths, which v1 removed (internal layout change);
// Vite tree-shakes these named imports so only the icons below ship in the bundle.
import React from 'react';
import {
  Badge,
  BadgeDollarSign,
  Bell,
  FileText,
  BadgeCheck,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleUserRound,
  ClipboardCheck,
  Clock3,
  Home,
  LayoutDashboard,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  Pencil,
  Phone,
  Plus,
  RefreshCcw,
  Search,
  ShieldCheck,
  SlidersHorizontal,
  Upload,
  Paperclip,
  Calculator,
  UserCog,
  UserPlus,
  Users,
  X,
} from 'lucide-react';

const icons = {
  badge: Badge,
  badgeDollar: BadgeDollarSign,
  bell: Bell,
  fileText: FileText,
  badgeCheck: BadgeCheck,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarClock,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clipboard: ClipboardCheck,
  clock: Clock3,
  close: X,
  dashboard: LayoutDashboard,
  home: Home,
  lock: LockKeyhole,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  refresh: RefreshCcw,
  search: Search,
  setting: SlidersHorizontal,
  shield: ShieldCheck,
  upload: Upload,
  paperclip: Paperclip,
  calculator: Calculator,
  user: CircleUserRound,
  userCog: UserCog,
  userPlus: UserPlus,
  users: Users,
};

export function Icon({ name, size = 18, strokeWidth = 2, ...props }) {
  const Component = icons[name] ?? Circle;
  return <Component aria-hidden="true" focusable="false" size={size} strokeWidth={strokeWidth} {...props} />;
}
