package th.co.glr.hr.payroll.export;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayInputStream;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Test;
import th.co.glr.hr.config.AppProperties;

/**
 * Checks for the SSO สปส.1-10 workbook. Two of these are golden reconciliations against GL&amp;R's
 * REAL filings — June and August 2026 — using the real amounts with synthetic identities (the repo
 * is public; national ids never land in it). Their per-branch เงินสมทบ totals are the figures on the
 * SSO's own สปส.1-10/1 receipt, so they only pass if the uncapped-ค่าจ้าง rule, the per-person
 * มาตรา 46 rounding and the branch split are all correct at once.
 */
class SsoExporterTest {
    private final SsoExporter exporter = new SsoExporter();

    private AppProperties.Employer employer() {
        AppProperties.Employer e = new AppProperties.Employer();
        e.setCompanyNameTh("บริษัท ทดสอบ จำกัด");
        e.setSsoEmployerAccount("0123456789");
        e.setSsoBranch("000000");
        e.setSsoRatePercent("5");
        return e;
    }

    // ---- golden reconciliations -------------------------------------------------------------

    /**
     * June 2026, the filing this workbook's layout was pinned to. Branch 000000 = 16 insured,
     * ค่าจ้าง 575,070, เงินสมทบ 13,725; branch 110001 = 11 insured, ค่าจ้าง 255,170, เงินสมทบ 8,863.
     * The ฿11,250 row in 110001 is the ฿562.50 → ฿563 rounding case.
     */
    @Test
    void juneGoldenReconciliationTwoBranchesRealAmountsSyntheticIdentities() {
        int[][] branch000000 = {
            {50369, 87500}, {124849, 87500}, {24400, 87500}, {20000, 87500}, {30000, 87500},
            {20850, 87500}, {35257, 87500}, {34738, 87500}, {21589, 87500}, {23400, 87500},
            {30875, 87500}, {42502, 87500}, {23738, 87500}, {12000, 60000}, {46600, 87500},
            {33903, 87500}
        };
        int[][] branch110001 = {
            {11250, 56250}, {45000, 87500}, {10000, 50000}, {20700, 87500}, {23620, 87500},
            {28500, 87500}, {32100, 87500}, {25500, 87500}, {18000, 87500}, {24500, 87500},
            {16000, 80000}
        };

        Workbook book = build(rowsFor(branch000000, branch110001));

        assertThat(sheetNames(book)).containsExactly("000000", "110001");
        assertSheet(book, "000000", 16, 575_070, 13_725);
        assertSheet(book, "110001", 11, 255_170, 8_863);
        // The ฿562.50-raw row must be FILED as ฿563 (มาตรา 46 วรรคท้าย), not ฿562.
        assertThat(contributionFor(book, "110001", 11_250)).isEqualTo(563.0);
    }

    /**
     * August 2026 (period_id 6), the first month generated by this exporter. Same 27 people and the
     * same per-branch เงินสมทบ as June — every ค่าจ้าง that moved belongs to a commission earner
     * already over the ฿17,500 ceiling — but eight ค่าจ้าง figures differ, so this is NOT a copy of
     * the June fixture: branch 000000's wage total moves 575,070 → 501,638 while its contribution
     * total stays 13,725. A bug that read the capped base instead of the gross would land both
     * months on the same wrong 17,500-flavoured total and fail here.
     */
    @Test
    void augustGoldenReconciliationRealAmountsSyntheticIdentities() {
        int[][] branch000000 = {
            {74792, 87500}, {49721, 87500}, {24400, 87500}, {20000, 87500}, {30000, 87500},
            {20850, 87500}, {34072, 87500}, {32862, 87500}, {19698, 87500}, {23400, 87500},
            {30875, 87500}, {28181, 87500}, {21862, 87500}, {12000, 60000}, {46600, 87500},
            {32325, 87500}
        };
        int[][] branch110001 = {
            {11250, 56250}, {45000, 87500}, {10000, 50000}, {20700, 87500}, {23620, 87500},
            {28500, 87500}, {32100, 87500}, {25500, 87500}, {18000, 87500}, {24500, 87500},
            {16000, 80000}
        };

        Workbook book = build(rowsFor(branch000000, branch110001));

        assertSheet(book, "000000", 16, 501_638, 13_725);
        assertSheet(book, "110001", 11, 255_170, 8_863);
        assertThat(total(book, "000000", 4) + total(book, "110001", 4))
            .as("total ค่าจ้าง filed for August").isEqualTo(756_808.0);
        assertThat(total(book, "000000", 5) + total(book, "110001", 5))
            .as("total เงินสมทบ filed for August").isEqualTo(22_588.0);
    }

    // ---- layout ------------------------------------------------------------------------------

    @Test
    void headerRowMatchesTheReferenceFilingsColumns() {
        Sheet sheet = build(List.of(insured("1111111111111", "15000.00", "750.00"))).getSheetAt(0);

        assertThat(cells(sheet.getRow(0)))
            .containsExactly("เลขบัตรประชาชน", "คำนำหน้า", "ชื่อ", "สกุล", "ค่าจ้าง", "เงินสมทบ");
    }

    /**
     * The reference filing orders each sheet by เลขบัตรประชาชน ascending, but {@code findExportRows}
     * hands rows over in {@code employee_code} order. The three ids below are deliberately supplied
     * in a DIFFERENT order from their sorted one, so a build that just echoed the caller's order
     * would fail this.
     */
    @Test
    void rowsAreOrderedByNationalIdAscendingNotByCallerOrder() {
        List<PayrollExportRow> rows = List.of(
            insured("3999999999999", "15000.00", "750.00"),
            insured("1111111111111", "15000.00", "750.00"),
            insured("2555555555555", "15000.00", "750.00"));

        Sheet sheet = build(rows).getSheetAt(0);

        assertThat(List.of(
                (long) sheet.getRow(1).getCell(0).getNumericCellValue(),
                (long) sheet.getRow(2).getCell(0).getNumericCellValue(),
                (long) sheet.getRow(3).getCell(0).getNumericCellValue()))
            .containsExactly(1111111111111L, 2555555555555L, 3999999999999L);
    }

    /** เลขบัตรประชาชน / ค่าจ้าง / เงินสมทบ must be real numeric cells, not text. */
    @Test
    void idAndAmountCellsAreNumericNotText() {
        Row row = build(List.of(insured("1111111111111", "15000.00", "750.00")))
            .getSheetAt(0).getRow(1);

        assertThat(row.getCell(0).getCellType()).isEqualTo(CellType.NUMERIC);
        assertThat(row.getCell(4).getCellType()).isEqualTo(CellType.NUMERIC);
        assertThat(row.getCell(5).getCellType()).isEqualTo(CellType.NUMERIC);
        assertThat(row.getCell(1).getCellType()).isEqualTo(CellType.STRING);
    }

    /**
     * คำนำหน้า is the Thai title WORD, which the .txt format could not carry (it wanted an SSO
     * 3-char code nobody had, and shipped three spaces). Asserting the word is present is the point.
     */
    @Test
    void titleColumnCarriesTheThaiTitleWord() {
        Row row = build(List.of(insured("1111111111111", "15000.00", "750.00")))
            .getSheetAt(0).getRow(1);

        assertThat(row.getCell(1).getStringCellValue()).isEqualTo("นางสาว");
        assertThat(row.getCell(2).getStringCellValue()).isEqualTo("ทดสอบ");
        assertThat(row.getCell(3).getStringCellValue()).isEqualTo("ระบบ");
    }

    // ---- branch split ------------------------------------------------------------------------

    @Test
    void eachBranchGetsItsOwnSheetHoldingOnlyItsOwnEmployees() {
        List<PayrollExportRow> rows = List.of(
            branched("1111111111111", "110001", "20000.00", "875.00"),
            branched("2222222222222", "000000", "30000.00", "875.00"),
            branched("3333333333333", "110001", "10000.00", "500.00"));

        Workbook book = build(rows);

        assertThat(sheetNames(book)).containsExactly("000000", "110001");
        assertThat(book.getSheet("000000").getLastRowNum()).as("1 header + 1 detail").isEqualTo(1);
        assertThat(book.getSheet("110001").getLastRowNum()).as("1 header + 2 details").isEqualTo(2);
        assertThat(total(book, "110001", 5)).isEqualTo(1_375.0);
        assertThat(total(book, "000000", 5)).isEqualTo(875.0);
    }

    @Test
    void allEmployeesUnassignedStillProducesExactlyOneSheetAtTheEmployerBranch() {
        List<PayrollExportRow> rows = List.of(
            insured("1111111111111", "20000.00", "875.00"),
            insured("2222222222222", "30000.00", "875.00"));

        Workbook book = build(rows);

        assertThat(sheetNames(book)).containsExactly("000000");
        assertThat(book.getSheet("000000").getLastRowNum()).isEqualTo(2);
    }

    @Test
    void noInsuredEmployeeStillProducesOneHeaderOnlySheet() {
        Workbook book = build(List.of(director("1111111111111")));

        assertThat(sheetNames(book)).containsExactly("000000");
        assertThat(book.getSheet("000000").getLastRowNum()).as("header row only").isZero();
    }

    @Test
    void directorsWithZeroContributionAreExcluded() {
        List<PayrollExportRow> rows = List.of(
            insured("1111111111111", "20000.00", "875.00"),
            director("2222222222222"));

        Sheet sheet = build(rows).getSheetAt(0);

        assertThat(sheet.getLastRowNum()).as("1 header + 1 insured, the director dropped").isEqualTo(1);
        assertThat((long) sheet.getRow(1).getCell(0).getNumericCellValue()).isEqualTo(1111111111111L);
    }

    // ---- the three amount rules --------------------------------------------------------------

    /**
     * ค่าจ้าง must be the wage actually paid, uncapped -- not the ฿17,500 capped {@code
     * sso_wage_base} the contribution math uses. The point of this test is that it is NOT 17,500.
     */
    @Test
    void wageIsTheUncappedGrossNotTheCappedBase() {
        Row row = build(List.of(uncapped("1111111111111", "124849.00", "17500.00", "875.00")))
            .getSheetAt(0).getRow(1);

        assertThat(row.getCell(4).getNumericCellValue()).isEqualTo(124_849.0);
        assertThat(row.getCell(4).getNumericCellValue()).isNotEqualTo(17_500.0);
        assertThat(row.getCell(5).getNumericCellValue()).as("เงินสมทบ still capped at 875")
            .isEqualTo(875.0);
    }

    /** ssoWageGross == null (rows processed before V123) falls back to ssoWageBase. */
    @Test
    void ssoWageGrossNullFallsBackToSsoWageBase() {
        Row row = build(List.of(insured("1111111111111", "15000.00", "750.00")))
            .getSheetAt(0).getRow(1);

        assertThat(row.getCell(4).getNumericCellValue()).isEqualTo(15_000.0);
    }

    /**
     * Wrong-way-round rounding, per มาตรา 46 วรรคท้าย: exactly .50 rounds UP, just-under-.50 rounds
     * DOWN. The three contributions are chosen so the SUM-OF-ROUNDED-PER-PERSON total (563 + 562 +
     * 301 = 1,426) differs from the ROUNDED-SUM-OF-RAW total (562.50 + 562.49 + 300.50 = 1,425.49 →
     * 1,425) — a fixture where the two agree would let a "round the total instead of each row" bug
     * pass by accident.
     */
    @Test
    void contributionRoundsPerPersonNotOnTheColumnTotal() {
        List<PayrollExportRow> rows = List.of(
            insured("1111111111111", "11250.00", "562.50"),  // exactly .50 -> UP to 563
            insured("2222222222222", "11249.80", "562.49"),  // just under .50 -> DOWN to 562
            insured("3333333333333", "6010.00", "300.50"));  // exactly .50 -> UP to 301

        // Rows sort by national id, so row 1/2/3 are the .50 / just-under / .50 cases in that order.
        // (Read by index, not by ค่าจ้าง: the first two wages both round to 11,250, so a lookup by
        // wage would be ambiguous.)
        Sheet sheet = build(rows).getSheetAt(0);

        assertThat(sheet.getRow(1).getCell(5).getNumericCellValue()).as("562.50 -> 563").isEqualTo(563.0);
        assertThat(sheet.getRow(2).getCell(5).getNumericCellValue()).as("562.49 -> 562").isEqualTo(562.0);
        assertThat(sheet.getRow(3).getCell(5).getNumericCellValue()).as("300.50 -> 301").isEqualTo(301.0);
        assertThat(total(sheet.getWorkbook(), "000000", 5))
            .as("sum of rounded rows, not rounded sum of raw").isEqualTo(1_426.0);
    }

    /** ค่าจ้าง rounds to whole baht too (owner ruling 2026-08-31), same HALF_UP direction. */
    @Test
    void wageRoundsToWholeBahtHalfUp() {
        List<PayrollExportRow> rows = List.of(
            uncapped("1111111111111", "20850.50", "17500.00", "875.00"),   // .50 -> UP
            uncapped("2222222222222", "20850.49", "17500.00", "875.00"));  // just under -> DOWN

        Workbook book = build(rows);

        assertThat(book.getSheet("000000").getRow(1).getCell(4).getNumericCellValue()).isEqualTo(20_851.0);
        assertThat(book.getSheet("000000").getRow(2).getCell(4).getNumericCellValue()).isEqualTo(20_850.0);
    }

    // ---- identity ----------------------------------------------------------------------------

    /**
     * เลขบัตรประชาชน keys on the NATIONAL ID (owner ruling 2026-08-03), not social_security_no. The
     * two ids below deliberately DIFFER — with a fixture where they match, this passes under either
     * preference and proves nothing.
     */
    @Test
    void keysOnNationalIdNotSocialSecurityNo() {
        PayrollExportRow row = row(1, null, "9000000000001", "9000000000002",
            "15000.00", null, "750.00");

        Sheet sheet = build(List.of(row)).getSheetAt(0);

        assertThat((long) sheet.getRow(1).getCell(0).getNumericCellValue()).isEqualTo(9000000000001L);
    }

    @Test
    void fallsBackToSocialSecurityNoWhenNationalIdIsMissing() {
        PayrollExportRow row = row(1, null, null, "9000000000002", "15000.00", null, "750.00");

        Sheet sheet = build(List.of(row)).getSheetAt(0);

        assertThat((long) sheet.getRow(1).getCell(0).getNumericCellValue()).isEqualTo(9000000000002L);
    }

    /** Neither id on file: the cell stays BLANK so the e-service rejects the row, rather than
     * filing a real person's wages under id 0. */
    @Test
    void bothIdsMissingLeavesTheCellBlankRatherThanZero() {
        PayrollExportRow row = row(1, null, null, null, "15000.00", null, "750.00");

        Cell cell = build(List.of(row)).getSheetAt(0).getRow(1).getCell(0);

        assertThat(cell.getCellType()).isEqualTo(CellType.BLANK);
    }

    // ---- helpers -----------------------------------------------------------------------------

    /** Runs the exporter and reads the bytes back as a real workbook — so every assertion above is
     * made against the file a user would actually download, not an in-memory model. */
    private Workbook build(List<PayrollExportRow> rows) {
        byte[] bytes = exporter.export(rows, employer());
        try {
            return new XSSFWorkbook(new ByteArrayInputStream(bytes));
        } catch (Exception e) {
            throw new IllegalStateException("exported bytes are not a readable xlsx", e);
        }
    }

    private List<PayrollExportRow> rowsFor(int[][] branch000000, int[][] branch110001) {
        List<PayrollExportRow> rows = new ArrayList<>();
        int seq = 0;
        for (int[] pair : branch000000) {
            rows.add(golden(++seq, "000000", pair[0], pair[1]));
        }
        for (int[] pair : branch110001) {
            rows.add(golden(++seq, "110001", pair[0], pair[1]));
        }
        return rows;
    }

    /** Real amounts, synthetic id — the repo is public, so no national id is ever committed. */
    private PayrollExportRow golden(int seq, String branch, int wageGross, int contributionTimes100) {
        return row(seq, branch, syntheticId(seq), syntheticId(seq),
            String.valueOf(Math.min(wageGross, 17500)),
            String.valueOf(wageGross),
            new BigDecimal(contributionTimes100).movePointLeft(2).toPlainString());
    }

    private String syntheticId(int seq) {
        return String.format("9%012d", seq);
    }

    private PayrollExportRow insured(String nationalId, String wageBase, String contribution) {
        return row(1, null, nationalId, nationalId, wageBase, null, contribution);
    }

    private PayrollExportRow branched(String nationalId, String branch, String wageBase, String contribution) {
        return row(1, branch, nationalId, nationalId, wageBase, null, contribution);
    }

    private PayrollExportRow uncapped(String nationalId, String wageGross, String wageBase, String contribution) {
        return row(1, null, nationalId, nationalId, wageBase, wageGross, contribution);
    }

    private PayrollExportRow director(String nationalId) {
        return row(1, null, nationalId, nationalId, "0.00", "0.00", "0.00");
    }

    private PayrollExportRow row(long id, String branch, String nationalId, String socialSecurityNo,
                                 String wageBase, String wageGross, String contribution) {
        return new PayrollExportRow(
            id, "E" + id, "นางสาว", "ทดสอบ", "ระบบ", null,
            nationalId, null, socialSecurityNo, null,
            null, null, null,
            BigDecimal.ZERO, BigDecimal.ZERO, BigDecimal.ZERO,
            money(wageBase), money(wageGross), money(contribution), branch);
    }

    private BigDecimal money(String value) {
        return value == null ? null : new BigDecimal(value);
    }

    private List<String> sheetNames(Workbook book) {
        List<String> names = new ArrayList<>();
        for (int i = 0; i < book.getNumberOfSheets(); i++) {
            names.add(book.getSheetName(i));
        }
        return names;
    }

    private List<String> cells(Row row) {
        List<String> values = new ArrayList<>();
        for (Cell cell : row) {
            values.add(cell.getStringCellValue());
        }
        return values;
    }

    /** Sums one numeric column down a sheet's detail rows — what the e-service itself totals. */
    private double total(Workbook book, String sheetName, int column) {
        Sheet sheet = book.getSheet(sheetName);
        double sum = 0;
        for (int i = 1; i <= sheet.getLastRowNum(); i++) {
            sum += sheet.getRow(i).getCell(column).getNumericCellValue();
        }
        return sum;
    }

    private void assertSheet(Workbook book, String sheetName, int insured, double wage, double contribution) {
        Sheet sheet = book.getSheet(sheetName);
        assertThat(sheet.getLastRowNum()).as("%s insured count", sheetName).isEqualTo(insured);
        assertThat(total(book, sheetName, 4)).as("%s total ค่าจ้าง", sheetName).isEqualTo(wage);
        assertThat(total(book, sheetName, 5)).as("%s total เงินสมทบ", sheetName).isEqualTo(contribution);
    }

    /** The เงินสมทบ filed for the (unique) row carrying the given ค่าจ้าง. */
    private double contributionFor(Workbook book, String sheetName, double wage) {
        Sheet sheet = book.getSheet(sheetName);
        for (int i = 1; i <= sheet.getLastRowNum(); i++) {
            if (sheet.getRow(i).getCell(4).getNumericCellValue() == wage) {
                return sheet.getRow(i).getCell(5).getNumericCellValue();
            }
        }
        throw new AssertionError("no row with ค่าจ้าง " + wage + " on sheet " + sheetName);
    }
}
