import { describe, expect, it } from 'vitest';
import { statusGroups } from './statusCatalog.js';
import {
  ATTENDANCE_CORRECTION_STATUS_LABEL_KEYS,
  COMMISSION_STATUS_LABEL_KEYS,
  FACTORY_QUOTE_STATUS_LABEL_KEYS,
  LEAVE_STATUS_LABEL_KEYS,
  OVERTIME_STATUS_LABEL_KEYS,
  PRICING_DECISION_STATUS_LABEL_KEYS,
  PRICING_REQUEST_STATUS_LABEL_KEYS,
  SPECIAL_MONEY_STATUSES,
  TICKET_PRIORITY_LABEL_KEYS,
  TICKET_STATUS_LABEL_KEYS,
  attendanceCorrectionStatusLabel,
  commissionStatusLabel,
  dealStageLabel,
  factoryQuoteStatusLabel,
  hasDealStageLabel,
  leaveStatusLabel,
  overtimeStatusLabel,
  pricingCostingStatusLabel,
  pricingDecisionStatusLabel,
  pricingRequestStatusLabel,
  roleLabel,
  specialMoneyStatusLabel,
  ticketPriorityLabel,
  ticketStatusLabel,
} from './format.js';

/**
 * THE GUARD THIS FILE EXISTS TO ADD.
 *
 * `format.js` hand-mirrors roughly ninety backend status constants across fourteen Thai label
 * maps, and until now nothing failed when a map and its backend type disagreed. The proof:
 * `factoryQuoteStatusLabel`'s `READY_FOR_COSTING` entry read "พร้อมคำนวณต้นทุน" for months after
 * V141 severed the costing aggregate — every `PricingCostingService` write now throws 409
 * `COSTING_MOVED_TO_CEO`, and the cost is computed by the CEO at `startReview` instead. The label
 * kept advertising a workflow step that no longer existed, and Import read the stale badge as the
 * request being stuck. It has since been relabelled by hand; the point of this file is that the
 * NEXT one is caught automatically instead.
 *
 * THE DIGEST. `docs/api/status-catalog.json` is generated by the backend's
 * `StatusCatalogContractTest` via reflection over the real Java status classes and enums — see
 * that class's own Javadoc for the enum-vs-String-constant split, which a naive source grep would
 * get silently wrong for four of the ten groups here. That test fails when the committed digest
 * drifts from what reflection finds today, so the JSON read below is not a transcription anyone
 * maintains by hand; it is the JVM introspecting its own status types, with a tripwire.
 *
 * TWO DIRECTIONS, both asserted, with a documented, self-cleaning exemption list on each side —
 * the same shape `serverContract.test.js` uses for `SERVER_ONLY`/`CALLS_DEPRECATED`:
 *
 *   1. Every backend status has a frontend label (`KNOWN_UNLABELLED` is the exemption list) — a
 *      new or renamed status must not silently render as its raw code.
 *   2. Every frontend label key still exists in the backend (`FRONTEND_ONLY_KEYS` is the exemption
 *      list) — a retired status must not linger as dead copy. This is the READY_FOR_COSTING shape
 *      in miniature: not a wrong LABEL (this guard cannot judge Thai wording, and does not try to
 *      — see "Do not change any label TEXT" in the task this file was built for) but a wrong KEY.
 *
 * HOW DIRECTION 1 IS TESTED: by calling the real exported function, not by inspecting a map
 * object. Every one of the ten functions below independently falls back to
 * `{ label: <the input, echoed back verbatim>, tone: <a fixed tone> }` when its internal map has
 * no entry — verified by reading each in format.js, not assumed. `isUnlabelled` below derives that
 * fallback's tone empirically (a sentinel probe) rather than hard-coding `'neutral'`, so it keeps
 * working even if a function's own fallback tone ever changes. This tests the actual RENDERING
 * behaviour a user would see, which is a strictly stronger claim than "this key is textually
 * present in the map somewhere".
 *
 * HOW DIRECTION 2 IS TESTED: each of the ten functions' backing map was lifted from a
 * function-local `const map` to a module-level const in format.js, with its key set exported
 * alongside (`*_LABEL_KEYS`, or `SPECIAL_MONEY_STATUSES` for the one map that already had a
 * same-shaped export). That refactor changes NO label text, NO tone, and NO runtime behaviour —
 * `format.test.js`'s existing 40 assertions pass unchanged against it — it only makes each map's
 * own key set enumerable without a second hand-typed copy. The alternative (regex-parsing
 * format.js's own source, the way `stageCatalog.test.js` parses `DealStage.java`) was considered
 * and rejected: format.js is the file under test, and parsing it blind would just be a second,
 * unguarded implementation of "what are this map's keys" sitting next to the first one.
 */

const GROUPS = statusGroups();

/**
 * Every map this digest covers, paired with its backend group name and the frontend function/key
 * list that back it. `keys` always comes from format.js's own `Object.keys(...)` export — never a
 * second hand-typed list — so there is nothing here for `keys` itself to drift from.
 */
const MAP_SPECS = [
  { name: 'ticketStatusLabel', labelFn: ticketStatusLabel, keys: TICKET_STATUS_LABEL_KEYS, group: 'TicketStatus' },
  { name: 'pricingRequestStatusLabel', labelFn: pricingRequestStatusLabel, keys: PRICING_REQUEST_STATUS_LABEL_KEYS, group: 'PricingRequestStatus' },
  { name: 'factoryQuoteStatusLabel', labelFn: factoryQuoteStatusLabel, keys: FACTORY_QUOTE_STATUS_LABEL_KEYS, group: 'FactoryQuoteStatus' },
  { name: 'pricingDecisionStatusLabel', labelFn: pricingDecisionStatusLabel, keys: PRICING_DECISION_STATUS_LABEL_KEYS, group: 'PricingDecisionStatus' },
  { name: 'commissionStatusLabel', labelFn: commissionStatusLabel, keys: COMMISSION_STATUS_LABEL_KEYS, group: 'CommissionStatus' },
  { name: 'ticketPriorityLabel', labelFn: ticketPriorityLabel, keys: TICKET_PRIORITY_LABEL_KEYS, group: 'Priority' },
  { name: 'overtimeStatusLabel', labelFn: overtimeStatusLabel, keys: OVERTIME_STATUS_LABEL_KEYS, group: 'OvertimeStatus' },
  { name: 'attendanceCorrectionStatusLabel', labelFn: attendanceCorrectionStatusLabel, keys: ATTENDANCE_CORRECTION_STATUS_LABEL_KEYS, group: 'AttendanceCorrectionStatus' },
  { name: 'specialMoneyStatusLabel', labelFn: specialMoneyStatusLabel, keys: SPECIAL_MONEY_STATUSES, group: 'SpecialMoneyStatus' },
  { name: 'leaveStatusLabel', labelFn: leaveStatusLabel, keys: LEAVE_STATUS_LABEL_KEYS, group: 'LeaveStatus' },
];

const specFor = (name) => MAP_SPECS.find((spec) => spec.name === name);

/** A value no real backend status will ever equal, used to learn each function's fallback shape. */
const UNKNOWN_SENTINEL = '__STATUS_CATALOG_UNKNOWN_PROBE__';

/**
 * True when `labelFn(code)` fell through to the generic "no entry for this key" branch, rather
 * than an intentional map entry — by calling the REAL function, not by inspecting its map. Derives
 * the fallback's tone from a sentinel probe instead of assuming `'neutral'`, so this keeps working
 * even if a function's own fallback tone ever changes.
 */
function isUnlabelled(labelFn, code) {
  const probe = labelFn(UNKNOWN_SENTINEL);
  const actual = labelFn(code);
  return actual.label === code && actual.tone === probe.tone;
}

// ─────────────────────────────────────────────────────────────────────────────
// Direction 1 exemptions — backend statuses with NO frontend label today
// ─────────────────────────────────────────────────────────────────────────────
//
// EMPTY, and that is the assertion — not an oversight.
//
// This guard found exactly two gaps on its first run, both in factoryQuoteStatusLabel:
// NOT_AVAILABLE and SUPERSEDED, each falling through to the raw-code fallback. SUPERSEDED was the
// live one: FactoryQuoteService calls quotes.supersede() on EVERY revised quote, and
// PricingRequestDetailPage renders quote history through that function unfiltered — so a second
// round of factory prices printed the literal English "SUPERSEDED" on a Thai screen, next to its
// own ครั้งที่ 1 badge. Same family as the READY_FOR_COSTING fossil, a MISSING label rather than a
// stale one.
//
// Both are now labelled (owner-chosen wording, 2026-08-16), so their entries are gone from here.
// That is the intended lifecycle: a gap is named loudly, then the entry disappears when it is
// fixed. Keep this constant rather than deleting it — the machinery is what lets the NEXT gap be
// recorded honestly instead of being quietly tolerated, and the emptiness is itself worth
// asserting: it says every backend status this digest covers currently has Thai copy.
const KNOWN_UNLABELLED = {};

// ─────────────────────────────────────────────────────────────────────────────
// Direction 2 exemptions — frontend label keys with no backend counterpart
// ─────────────────────────────────────────────────────────────────────────────
//
// Same spirit as serverContract.test.js's SERVER_ONLY: every entry names a real, still-divergent
// key and carries a reason, and the self-cleaning test below deletes it the moment it stops being
// true. All three are pricingRequestStatusLabel entries format.js already documents inline as
// deliberately retained through a deploy-before-migration window and for historical event rows —
// this list is what lets the digest guard agree with those existing comments instead of
// contradicting them.
const FRONTEND_ONLY_KEYS = {
  pricingRequestStatusLabel: {
    COSTING_IN_PROGRESS:
      'Retired by V140 (merged into AWAITING_FACTORY_RESPONSE, dropped from the DB constraint) — '
      + 'no Java constant of this name exists any more, so reflection correctly never produces it. '
      + 'Kept in the frontend map per its own inline comment: rows can sit in it during the '
      + 'deploy-before-migration window, and historical pricing_request_event rows keep the old '
      + 'value forever. Deliberate and permanent, not drift.',
    COSTING_REVISION_REQUIRED:
      'Retired by V141 (the CEO owns costing now; PricingDecisionService.returnToImport routes '
      + 'straight to AWAITING_FACTORY_RESPONSE). Kept for the identical '
      + 'deploy-before-migration-window and historical-event-row reasons as COSTING_IN_PROGRESS.',
    MORE_INFO_REQUIRED:
      'Retired by V140 along with the ขอข้อมูลเพิ่มเติม feature entirely. Kept for the same '
      + 'deploy-before-migration-window and historical-event-row reasons as its two neighbours.',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Maps deliberately NOT covered by this digest
// ─────────────────────────────────────────────────────────────────────────────
//
// An honest documented exclusion, never a silent skip — each names the map, the investigation
// behind it, and (where investigation turned up something) the finding, un-fixed, for a reviewer
// to act on.
const EXCLUDED_MAPS = {
  roleLabel:
    'No single backend status-constants type to pin against. The live role vocabulary is produced '
    + "by DivisionAccessPolicy.roleFor()'s branch logic — inline string literals inside an "
    + 'if/else derivation over division+position data, not a declared constants class with a '
    + 'VALUES/VALID field the way the other nine groups are. A separate class, ApplicationRoles, '
    + 'does hold a static 9-role allowlist (ApplicationRoles.priority()) for a different purpose '
    + '(validating an already-assigned role), and it is not proven to be kept in lockstep with '
    + "DivisionAccessPolicy's actual return values by any existing guard — auditing THAT "
    + 'relationship is a distinct, adjacent concern outside this scope. Investigated anyway '
    + "(2026-08-16): ApplicationRoles.priority() has no 'account' counterpart in roleLabel's map "
    + "(falls through to the generic .toUpperCase() fallback, which happens to render legibly as "
    + "'ACCOUNT'), and roleLabel carries an 'admin' key that appears in no backend source at all — "
    + 'DivisionAccessPolicy.roleFor never returns it and ApplicationRoles does not list it. Both '
    + 'are real, reported here rather than fixed (no label-text changes), and excluded because '
    + 'there is no single authoritative type to build a reflection-based guard against without '
    + 'also taking on the separate ApplicationRoles-vs-DivisionAccessPolicy question.',
  pricingCostingStatusLabel:
    'sales.pricing_costing.status has no backing Java type at all post-V141 — confirmed by '
    + 'reading every file under backend/.../pricingcosting/: no PricingCostingStatus class or enum '
    + 'exists anywhere in the tree. Its only formal declaration is the '
    + 'chk_pricing_costing_status CHECK constraint in '
    + "V61__factory_quote_costing_foundation.sql ('DRAFT','CALCULATED','SUBMITTED','SUPERSEDED',"
    + "'CANCELLED'), a SQL text artifact reflection has no access to — and a migration is immutable "
    + 'once applied, so a regex anchored to V61 would go stale the moment a LATER migration '
    + 're-declares the constraint. Investigated anyway: the map covers 4 of the 5 CHECK values '
    + '(missing SUPERSEDED), but grepping every pricing_costing write site '
    + '(PricingCostingRepository.createComputed, and PricingRequestRepository\'s '
    + 'cancelOpenChildrenForDeadRequest/cancelOpenStep2Children cascades) found none ever writes '
    + "'SUPERSEDED' to this column — every cascade writes 'CANCELLED' instead, so unlike the "
    + 'factoryQuoteStatusLabel gap in KNOWN_UNLABELLED above, this one looks currently dormant, '
    + 'not live. Reported, not guarded — there is no Java source to reflect on.',
  'hasDealStageLabel / dealStageLabel':
    'DealStage already has a stronger guard than a digest entry would add. It is served live at '
    + 'GET /api/meta/deal-stages (DealStageMetaController), checked at RUNTIME on every fetch of '
    + "that catalog by stageMeta.js's assertStageLabelsComplete (throws in dev/test, "
    + 'console.error in prod), and checked at BUILD TIME by '
    + "features/tickets/stageCatalog.test.js, which reads DealStage.java directly out of the "
    + 'backend source tree (with its own anti-vacuity floor) and asserts hasDealStageLabel for '
    + 'every code in DealStage.ORDER — and, unlike a plain digest, also checks gate/phase/'
    + 'businessCode/auto structurally. A third mirror here would not close a gap; it would just be '
    + 'one more copy of the same fifteen codes to keep in sync.',
};

describe('status catalog digest — harness sanity', () => {
  // These run first so a digest that failed to load, or a format.js export that came back
  // undefined, fails LOUDLY instead of letting every assertion below pass vacuously.
  it('read a plausible digest', () => {
    expect(Object.keys(GROUPS).length).toBeGreaterThanOrEqual(10);
    const total = Object.values(GROUPS).reduce((sum, list) => sum + list.length, 0);
    expect(total).toBeGreaterThan(50);
  });

  it('every covered map resolves to a non-empty backend group and a non-empty key list', () => {
    for (const spec of MAP_SPECS) {
      expect(GROUPS[spec.group], `digest has no group "${spec.group}" for ${spec.name}`).toBeDefined();
      expect(GROUPS[spec.group].length, `${spec.group} is empty`).toBeGreaterThan(0);
      expect(spec.keys.length, `${spec.name}'s own key list is empty`).toBeGreaterThan(0);
    }
  });

  it('the sentinel-probe technique detects an unknown code as unlabelled', () => {
    for (const spec of MAP_SPECS) {
      expect(isUnlabelled(spec.labelFn, `${UNKNOWN_SENTINEL}_2`), spec.name).toBe(true);
    }
  });

  it('the sentinel-probe technique does NOT flag a real labelled code', () => {
    // The other half of the anti-vacuity check on the technique itself: a probe that always
    // returned true would make direction 1 below pass on every status, checking nothing.
    expect(isUnlabelled(ticketStatusLabel, 'draft')).toBe(false);
    expect(isUnlabelled(overtimeStatusLabel, 'SUBMITTED')).toBe(false);
    expect(isUnlabelled(specialMoneyStatusLabel, 'CANCELLED')).toBe(false);
  });
});

describe('direction 1 — every backend status has a frontend label', () => {
  it('no backend status renders as its own raw code, undocumented', () => {
    const missing = [];
    for (const spec of MAP_SPECS) {
      const exemptions = KNOWN_UNLABELLED[spec.name] ?? {};
      for (const code of GROUPS[spec.group]) {
        if (exemptions[code]) continue;
        if (isUnlabelled(spec.labelFn, code)) {
          missing.push(`${spec.name}: ${spec.group}.${code}`);
        }
      }
    }
    expect(
      missing,
      'backend statuses with no frontend label and no KNOWN_UNLABELLED entry — a new or renamed '
      + 'status renders as its raw code to the user. Add a Thai label in format.js, or if it is '
      + 'genuinely not reachable from any screen yet, document it in KNOWN_UNLABELLED with a reason.',
    ).toEqual([]);
  });
});

describe('direction 2 — every frontend label key still exists in the backend', () => {
  it('no frontend label key is dead copy for a retired/renamed status, undocumented', () => {
    const stale = [];
    for (const spec of MAP_SPECS) {
      const backendCodes = new Set(GROUPS[spec.group]);
      const exemptions = FRONTEND_ONLY_KEYS[spec.name] ?? {};
      for (const key of spec.keys) {
        if (backendCodes.has(key)) continue;
        if (exemptions[key]) continue;
        stale.push(`${spec.name}: ${key}`);
      }
    }
    expect(
      stale,
      'frontend label keys with no backend counterpart and no FRONTEND_ONLY_KEYS entry — a '
      + 'retired status lingering as dead copy (the READY_FOR_COSTING shape, on a KEY instead of '
      + 'text). Delete the entry from format.js, or if it is a deliberate historical/fallback key, '
      + 'document it in FRONTEND_ONLY_KEYS with a reason.',
    ).toEqual([]);
  });
});

describe('exemption lists stay honest', () => {
  it('every KNOWN_UNLABELLED entry names a real map, a real backend status, and is still unlabelled', () => {
    const stale = [];
    for (const [specName, entries] of Object.entries(KNOWN_UNLABELLED)) {
      const spec = specFor(specName);
      expect(spec, `KNOWN_UNLABELLED names "${specName}", which is not a covered map`).toBeTruthy();
      const backendCodes = new Set(GROUPS[spec.group]);
      for (const [code, reason] of Object.entries(entries)) {
        expect(reason.length, `KNOWN_UNLABELLED["${specName}"]["${code}"] needs a reason`).toBeGreaterThan(20);
        if (!backendCodes.has(code)) {
          stale.push(`${specName}.${code} — no longer a backend status; delete the entry`);
        } else if (!isUnlabelled(spec.labelFn, code)) {
          stale.push(`${specName}.${code} — now has a real label; delete the entry`);
        }
      }
    }
    expect(stale).toEqual([]);
  });

  it('every FRONTEND_ONLY_KEYS entry names a real map, a real map key, and is still absent from the backend', () => {
    const stale = [];
    for (const [specName, entries] of Object.entries(FRONTEND_ONLY_KEYS)) {
      const spec = specFor(specName);
      expect(spec, `FRONTEND_ONLY_KEYS names "${specName}", which is not a covered map`).toBeTruthy();
      const backendCodes = new Set(GROUPS[spec.group]);
      for (const [key, reason] of Object.entries(entries)) {
        expect(reason.length, `FRONTEND_ONLY_KEYS["${specName}"]["${key}"] needs a reason`).toBeGreaterThan(20);
        if (!spec.keys.includes(key)) {
          stale.push(`${specName}.${key} — no longer a label key; delete the entry`);
        } else if (backendCodes.has(key)) {
          stale.push(`${specName}.${key} — the backend defines it again; delete the entry`);
        }
      }
    }
    expect(stale).toEqual([]);
  });
});

describe('maps deliberately not covered by this digest', () => {
  it('every EXCLUDED_MAPS entry names a real export and carries a reason', () => {
    // roleLabel / pricingCostingStatusLabel / hasDealStageLabel / dealStageLabel must still exist
    // as exports — if one is renamed or removed, the exclusion above is talking about nothing.
    expect(typeof roleLabel).toBe('function');
    expect(typeof pricingCostingStatusLabel).toBe('function');
    expect(typeof hasDealStageLabel).toBe('function');
    expect(typeof dealStageLabel).toBe('function');
    for (const [name, reason] of Object.entries(EXCLUDED_MAPS)) {
      expect(reason.length, `EXCLUDED_MAPS["${name}"] needs a reason`).toBeGreaterThan(40);
    }
  });
});
