#!/usr/bin/env python3
"""Regenerate checked-in geography snapshot and Flyway repeatable seed. No runtime network use."""
import argparse
import json
from pathlib import Path
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[2]
REVISION = 'eef739a534e26181c86073d69e9aeb527110cf1a'
BASE = f'https://raw.githubusercontent.com/open-admin-data/thailand-administrative-divisions/{REVISION}/data'
parser = argparse.ArgumentParser()
parser.add_argument('--source-dir', type=Path, help='Offline directory containing all-*.json source files')
args = parser.parse_args()
def source(kind):
    filename = f'all-{kind}.json'
    return json.loads((args.source_dir / filename).read_bytes() if args.source_dir else urllib.request.urlopen(f'{BASE}/{filename}', timeout=60).read())
def names(row):
    return dict(code=row['code']['dopa'], nameTh=re.sub(r'^(จังหวัด|อำเภอ|เขต|ตำบล|แขวง)\s*', '', row['name']['th']).strip(), nameEn=row['name']['en'])
provinces = [names(r) for r in source('provinces')]
districts = [dict(**names(r), provinceCode=r['parent']['id']) for r in source('districts')]
subdistricts = [dict(**names(r), districtCode=r['parent']['id'], provinceCode=r['ancestors'][0]['id'], postalCodes=sorted(set(r.get('zip_codes', [])))) for r in source('subdistricts')]
pids = {r['code'] for r in provinces}
dmap = {r['code']:r['provinceCode'] for r in districts}
assert len(pids) == len(provinces) == 77
assert len(dmap) == len(districts)
assert len({r['code'] for r in subdistricts}) == len(subdistricts)
assert all(r['provinceCode'] in pids for r in districts)
assert all(dmap[r['districtCode']] == r['provinceCode'] for r in subdistricts)
assert all(re.fullmatch(r'\d{5}', p) for r in subdistricts for p in r['postalCodes'])
data = dict(sourceRevision=REVISION, provinces=provinces, districts=districts, subdistricts=subdistricts)
(ROOT/'frontend/src/data/thai-locations.json').write_text(json.dumps(data,ensure_ascii=False,separators=(',',':'))+'\n')
def quote(x): return "'"+x.replace("'","''")+"'"
lines = [f'-- Generated by scripts/thai-address/import.py; source revision {REVISION}.', '-- CC-BY-4.0 open-admin-data/thailand-administrative-divisions; see scripts/thai-address/README.md.']
for table,rows,cols in [('thai_provinces',provinces, [('code','code'),('name_th','nameTh'),('name_en','nameEn')]),('thai_districts',districts,[('code','code'),('province_code','provinceCode'),('name_th','nameTh'),('name_en','nameEn')]),('thai_subdistricts',subdistricts,[('code','code'),('district_code','districtCode'),('province_code','provinceCode'),('name_th','nameTh'),('name_en','nameEn')])]:
    lines.append(f'INSERT INTO customers.{table} ({", ".join(c for c,k in cols)}) VALUES')
    lines.append(',\n'.join('('+','.join(quote(r[k]) for c,k in cols)+')' for r in rows))
    lines.append('ON CONFLICT (code) DO UPDATE SET '+', '.join(f'{c}=EXCLUDED.{c}' for c,k in cols if c!='code')+';')
lines.append('INSERT INTO customers.thai_subdistrict_postal_codes (subdistrict_code, postal_code) VALUES')
lines.append(',\n'.join(f'({quote(r["code"])},{quote(p)})' for r in subdistricts for p in r['postalCodes']))
lines.append('ON CONFLICT DO NOTHING;')
(ROOT/'backend/src/main/resources/db/migration/R__thai_locations.sql').write_text('\n'.join(lines)+'\n')
print(f'Generated {len(provinces)} provinces, {len(districts)} districts, {len(subdistricts)} subdistricts')
