import { backendOperations } from '../../src/api/apiSurface.js';

// The API surface, derived from the BACKEND — not from the frontend's route table.
//
// ── Why this changed ─────────────────────────────────────────────────────────
// This file used to walk `API_ROUTES`, on the reasoning that a hand-listed set of endpoints goes
// stale and a coverage suite that silently stops covering new code is worse than none. The
// reasoning was right; the source was wrong. API_ROUTES is what hrApi.js CALLS — a consumer of
// the API, not the API. An endpoint no frontend route happened to call was invisible here, which
// is precisely the endpoint nothing else covers either.
//
// A 2026-08-14 audit that drove all 278 declared endpoints measured the gap:
//
//   • 49 backend endpoints were absent from this surface entirely
//   • 24 more were swept under a verb they do not implement
//   • `routes.js`'s `action: (id, action) => /api/tickets/${id}/${action}` collapsed ~22 real
//     deal actions (cancel, hold, lost, stage, reopen, close/verify, …) into ONE synthetic path,
//     `/api/tickets/999999/999999`, because the walker filled both slots with the same
//     placeholder. That path matches no controller — yet it answered 401 anonymously and 404
//     authenticated, satisfying every assertion in api-surface.spec.js while exercising nothing.
//
// The surface now comes from `docs/api/api-surface.json`, generated by ApiSurfaceContractTest
// from springdoc's /v3/api-docs — Spring's own handler mappings, i.e. what the app dispatches.
// That test fails if the digest drifts from the running app, so a new endpoint is in scope here
// the moment it exists, and no one has to remember anything.
//
// Each endpoint is now also swept with ITS OWN declared verb, so a refusal is the answer to the
// question actually asked. The old file had to infer verbs by parsing hrApi.js's `method:` option
// bags, which is why 23 routes resolved no verb at all and were skipped by the authenticated sweep.

/** Matches no row. Every assertion here is about the auth/permission layers, which run first. */
const PLACEHOLDER_ID = 999_999;
const PLACEHOLDER_DATE = '2026-01-01';

/** Path params that are dates, not ids — substituting 999999 makes them 400 on type conversion. */
const DATE_PARAMS = /^(date|effectiveDate|payrollMonth)$/i;

function concretePath(templatePath) {
  return templatePath.replace(/\{([^}]+)\}/g, (_, name) =>
    DATE_PARAMS.test(name) ? PLACEHOLDER_DATE : String(PLACEHOLDER_ID));
}

/**
 * Every operation the backend serves, as `{ name, path, verb, template }`.
 *
 * `name` is the canonical `VERB /template/{path}` so a failure names the endpoint as the backend
 * declares it, not as some frontend alias.
 */
export function apiSurface() {
  return backendOperations()
    .map(({ verb, path }) => ({
      name: `${verb} ${path}`,
      template: path,
      verb,
      path: concretePath(path),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

// SecurityConfig's anonymous allowlist, mirrored exactly. Anything here is reachable without a
// session BY DESIGN; everything else in the surface must answer 401. Keeping the list here (and
// asserting it, rather than just skipping these paths) means widening the real allowlist without
// updating this constant fails the suite — which is the direction that matters, since a new
// permitAll() line is precisely the change that should never pass unnoticed.
export const ANONYMOUS_ALLOWLIST = [
  // POST /api/auth/login — no session exists yet, by definition.
  '/api/auth/login',
  // POST /api/attendance/punch — scanner devices authenticate with X-GLR-Agent-Token, not a
  // session, so the filter chain cannot gate it.
  '/api/attendance/punch',
];

// Endpoints excluded from the per-role authenticated sweep (they are still covered by the
// anonymous 401 sweep, which costs one rejected request each). These render or stream a document
// — a PDF, a ZIP of payslips, a bank/tax export file — so hitting them once per role would
// dominate the suite's runtime and, for the LibreOffice-backed renderers, shell out to `soffice`
// each time. Their AUTHORIZATION is still asserted anonymously; only the authenticated fetch is
// skipped.
const HEAVY_PATH_PATTERNS = [/\.pdf$/, /\.zip$/, /\/export\//, /\/file$/, /proforma/];

export function isHeavyPath(path) {
  return HEAVY_PATH_PATTERNS.some((pattern) => pattern.test(path));
}

/** The GET subset — swept per role for server errors. */
export function readableSurface() {
  return apiSurface().filter((entry) => entry.verb === 'GET');
}

/**
 * Write endpoints that address a resource by id — the safe subset to sweep for authorization.
 *
 * Safe because the id is a placeholder that matches no row: every one of these is an action on
 * an existing resource, so with a non-existent id the service can only refuse (403) or fail to
 * find it (404). It cannot mutate a real row, and it cannot create the parent it was asked to
 * act on. Collection-level writes (`POST /api/employees`, `POST /api/overtime`) are deliberately
 * excluded — those genuinely can create something, so sweeping them across every role would mean
 * writing rows into a shared database to find out who is allowed to.
 */
export function writeEndpointsWithId() {
  return apiSurface()
    .filter((entry) => entry.verb !== 'GET' && /\{[^}]+\}/.test(entry.template))
    .map(({ name, path, verb }) => ({ name, path, verb }));
}
